backend/build.gradle
backend/src/main/java/peer/backend/config/SecurityConfig.java
backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
backend/src/main/java/peer/backend/controller/LoginController.java
backend/src/main/java/peer/backend/controller/MemberController.java
backend/src/main/java/peer/backend/dto/security/Message.java
backend/src/main/java/peer/backend/dto/security/request/ToReissueTokens.java
backend/src/main/java/peer/backend/dto/security/response/ErrorDto.java
backend/src/main/java/peer/backend/repository/user/TokenRepository.java
backend/src/main/java/peer/backend/service/LoginService.java
backend/src/main/java/peer/backend/service/MemberService.java
backend/src/main/resources/application.yml
backend/src/test/java/peer/backend/config/jwt/TokenProviderTest.java
backend/src/test/java/peer/backend/service/LoginServiceTest.java

로그인 이후, JWT Access token이 만료되었을 경우, 해당 API를 호출해 Access token을 재발급합니다.
<br><br><br>
* Access token을 재발급하는 sevice의 테스트 결과 입니다.
* Postman으로 테스트한 결과 입니다.

[Feat] JWT Access token 재발급 API 구현

---

backend/src/main/java/peer/backend/controller/board/RecruitController.java
backend/src/main/java/peer/backend/dto/board/recruit/TagListResponse.java
backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java

* 모집게시글 작성시 필요한 tagList를 반환합니다.
* 해당 메소드는 2스텝에서 admin에 tagList 관리 기능이 추가됐을 때 함께 수정이 필요합니다.
* getTagListForWrite와 getTagListForEdit은 기능적으로 동일하나 추후 글의 생성, 수정 기능이 달라지게 될 것을 대비하여 일단 api를 분리해 두었습니다.
* getTagListForEdit은 이전 merge가 완료되면 @AthorCheck 어노테이션으로 글작성자 여부를 검사할 예정입니다.
<br><br><br>
postman

[FEAT] #185 tagList related method add

---

backend/src/main/java/peer/backend/annotation/AuthorCheck.java
backend/src/main/java/peer/backend/aspect/AuthorCheckAspect.java
backend/src/main/java/peer/backend/controller/board/RecruitController.java

author 확인 반복작업을 위한 annotation을 추가하기 위하여
annotation 패키지에 AuthorCheck 인터페이스,
aspect 패키지에 AuthorCheckAspect 를 추가하였습니다.
aspect에서 recruitRepository를 주입하여
authentication의 유저 닉네임과 recruit의 writer_nickname을 비교하여 
일치하지 않을 경우
Forbidden 403 에러를 반환,
존재하지 않는 게시글인 경우
NotFoundException 404 에러를 반환합니다.
<br><br><br>
postman

[FEAT]  #179 author check annotation add

---

backend/src/main/java/peer/backend/controller/message/MessaageController.java
backend/src/main/java/peer/backend/dto/message/KeywordDTO.java
backend/src/main/java/peer/backend/dto/message/MsgContentDTO.java
backend/src/main/java/peer/backend/repository/user/UserRepository.java

- DTO 중 클라이언트 측에서 전달하는 데이터들의 유효성 관련하여 검사진행함
- Msg 관련하여 빈쪽지 처리, 허용길이 300자 제한, 쪽지 보낼시의 Id 지정 등을 valid annotation으로 처리함
- 쪽지 대상 검색 기능에서 이메일을 허용시 @ 와 g 같은 걸 넣으면, 불특정 다수 전체를 긁어낼 수 있는 문제 발견함.
- 이에 오로지 닉네임으로만 확인이 가능하도록 바꿈
- 특수문자 정규식으로 사용 불가능하게 지정함
- 검색 키워드는 최소 2자, 최대 10자로 제한함
<br><br><br>

[REFACTOR] Haryu specific validation update

---

backend/src/main/resources/application-dev.yml

구글 api 콘솔에는 도메인으로만 리다이렉트 URL을 입력할 수 있는데 별도의 설정을 안하면 리다이렉트 URL이 호스트 IP로 잡혀서 에러가 났습니다.
그래서 리다이렉트 URL을 명시적으로 추가해주었습니다.
<br><br><br>

[FIX] ouath google redirect url 추가

---

backend/src/main/java/peer/backend/controller/message/MessaageController.java
backend/src/main/java/peer/backend/exception/AlreadyDeletedException.java
backend/src/main/java/peer/backend/service/message/MessageMainService.java
backend/src/main/java/peer/backend/service/message/MessageSubService.java

- 원래는 한 사람이 삭제를 하더라도 대화가 남고, 메시지를 보낼 수 있었음
- 이는 로직적 헛점 + 에러 상황이 발생함. -> 이에 메시지 Index 는 삭제하되, 삭제하지 않은 사람은 메시지를 받아 보는 것은 가능하게 두되, 새로운 메시지 전달이 안되도록 막아둠
- 이때 사용하는 HTTP status 는 UNAVAILABLE_FOR_LEGAL_REASONS 으로 반환하는 것으로 수정함
<br><br><br>

[HOTFIX] deleted message recovery strategy block deleted case

---

backend/build.gradle
backend/src/main/java/peer/backend/config/JasyptConfig.java
backend/src/main/resources/application-local.yml

- 기존의 메일 계정을 peer계정으로 변경했습니다.
- peer계정의 비밀번호를 암호화 해서 yml 파일 안에 저장했습니다.
- 그리고, JasyptConfig를 추가해서 복호화해서 전송할 수 있도록 했습니다.
<br><br><br>

fix: encrypt the password for the peer account

---

backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
backend/src/main/java/peer/backend/controller/socket/SocketIoServerController.java
backend/src/main/java/peer/backend/dto/socket/tempDTO.java
backend/src/main/java/peer/backend/service/socket/SocketServerService.java

- 소켓 커넥션 연결 컨트롤러 구성 완료
- 소켓 커넥션 연결 서비스 구성 완료
- 서비스에서 의존성 주입을 통해 online 여부 파악 가능하도록 구성 완료
- 기존 valid access token 의 문제점 발견하여 임시로 valid 방식을 바꿔서 구성 완료
<br><br><br>
- socket.io 를 통한 커넥션 연결 확인 완료 
- service 내부의 isOnline 메서드 점검 완료 
- redis 캐쉬에 정상 등록 여부 확인 완료

FEAT: primitive socket controller and service finished

---

backend/src/main/java/peer/backend/dto/profile/response/PersonalInfoResponse.java
backend/src/main/java/peer/backend/repository/user/SocialLoginRepository.java
backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java

- authentication을 authenticationFt 와 authenticationGoogle로 나누었습니다.
- authenticationFt는 42 인트라를 가지도록, authenticationGoogle은 gmail 주소를 가지도록 했습니다.
<br><br><br>

407 hotfix personal auth

---

backend/build.gradle
backend/src/main/java/peer/backend/controller/board/RecruitController.java
backend/src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
backend/src/main/java/peer/backend/dto/board/recruit/RecruitListRequest.java
backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
backend/src/main/java/peer/backend/entity/board/recruit/enums/RecruitDueEnum.java
backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java

- due 기간 검색을 위하여 string과 int값을 갖는 RecruitDueEnum 추가 -> dto, entity가 해당 enum을 사용하도록 수정
- due 기간 검색을 위하여 Recruit엔티티에 dueValue필드 추가,  RecruitListRequestDto에 start, end field 추가.
두 값 모두 due의 enumType의 value값을 저장함
- favorite 기능 사용시 principal 대신 auth 사용하도록 수정
- recruit OneToMany를 갖는 하위 엔티티들의 cascade를 all로 수정
- recruitApply시에 role이 null값이 경우 id라서 Null이 허용되지 않아 null이 들어올 경우 ""를 입력하도록 수정
<br><br><br>

[HOTFIX] #405 메인페이지에서 모집글 검색시 due를 기간으로 검색하기

---

backend/src/main/java/peer/backend/controller/SignUpController.java
backend/src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
backend/src/main/java/peer/backend/service/EmailAuthService.java
backend/src/main/java/peer/backend/service/MemberService.java
backend/src/main/java/peer/backend/service/SocialLoginService.java
backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java

- OAuth 로그인 한 소셜 계정 이메일과 회원가입 시 적는 이메일이 동일할때 발생하던 문제 해결
- 이미 소셜 계쩡이 연동이 되었는데 또 해당 소셜 서비스로 또 연동을 시도할 경우 막는 로직 추가
- 레디스 사용하던 부분 짜잘 리팩토링(서비스 내의 함수로 래핑함)
<br><br><br>

[FIX] OAuth 예외 상황 처리

---

src/main/java/peer/backend/service/ExcelService.java

기존에 XSSFWorkbook를 close 하지 않아(XSSFWorkbook가 Closble을 상속받은 인터페이스의 구현체라 close를 해줘야 하나 봅니다.) 에러가 잡혀 close를 추가해주었습니다.
<br><br><br>

[FIX] XSSFWorkbook close

---

src/main/java/peer/backend/config/jwt/TokenProvider.java
src/main/java/peer/backend/controller/SignInController.java
src/main/java/peer/backend/dto/security/request/AdminLoginRequest.java
src/main/java/peer/backend/entity/user/Admin.java
src/main/java/peer/backend/entity/user/Login.java
src/main/java/peer/backend/entity/user/User.java
src/main/java/peer/backend/oauth/PrincipalDetails.java
src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
src/main/java/peer/backend/repository/user/AdminRepository.java
src/main/java/peer/backend/service/AdminService.java
src/main/java/peer/backend/service/LoginService.java

#488 
어드민 테이블을 만들고 해당 테이블에 어드민 계정을 저장합니다.
다만 Spring Security에서 User든 Admin이든 이를 일괄적으로 처리할 수 있어야 하므로 두 엔티티가 Login Interface를 구현하도록 하여 이를 해결하였습니다.
이에따라 TokenProvider에서 User와 Admin을 모두 처리할수있도록 수정하였습니다
<br><br><br>
포스트맨으로 테스트하였습니다.

[FEATURE] Admin Login

---

src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java

모집글 생성시 RoleList가 비어있을 때 leaderJob 할당을 무시하기 위하여
조건문에 RoleList.isEmpty를 추가하였습니다.
<br><br><br>

hotfix-check roleList empty when leaderJob is empty

---

src/main/java/peer/backend/controller/team/TeamController.java
src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
src/main/java/peer/backend/dto/team/TeamJobDto.java
src/main/java/peer/backend/entity/board/recruit/Recruit.java
src/main/java/peer/backend/entity/board/recruit/RecruitFavorite.java
src/main/java/peer/backend/entity/composite/TeamUserJobPK.java
src/main/java/peer/backend/entity/team/Team.java
src/main/java/peer/backend/entity/team/TeamJob.java
src/main/java/peer/backend/entity/team/TeamUser.java
src/main/java/peer/backend/entity/team/TeamUserJob.java
src/main/java/peer/backend/repository/board/recruit/RecruitApplicantRepository.java
src/main/java/peer/backend/repository/team/TeamUserJobRepository.java
src/main/java/peer/backend/repository/team/TeamUserRepository.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java
src/main/java/peer/backend/service/team/TeamService.java
src/test/java/peer/backend/team/TeamRepositoryTest.java
src/test/java/peer/backend/team/TeamUserRepositoryTest.java

- teamUserJob으로 teamUser와 teamJob을 ManyToMany로 연결
- teamUserJob에서 teamUserStatus로 지원자 상태를 관리
- 모집글 상세조회시 팀의 목표 인원(totalNumber)와 현재 인원(current), 각 역할의 목표 인원(role.max)과 현재 인원(role.current)를 반환
<br><br><br>

[FIX] 모집글 작성 및 지원시 역할 서비스 로직 수정

---

src/main/java/peer/backend/controller/message/MessaageController.java
src/main/java/peer/backend/dto/message/TargetForDelete.java
src/main/java/peer/backend/repository/message/MessageIndexRepository.java
src/main/java/peer/backend/service/message/MessageMainService.java

- A, B가 대화중에 B가 대화를 삭제한다. 이때 A 혹은 B가 새롭게 대화를 동일한 상대와 하도록 메시지를 보내게 되면, 최초 메시지는 전달 됨. 그러나 이후 새로운 대화방 메시지 전달이 안됨. 
- 더불어 삭제도 정상적으로 처리 되지 않음 
- 프론트에서 conversationId 로 로직 변경된 것에 대응하여 DTO 수정 
- 이에 따라 삭제 비즈니스 로직의 삭제 로직 변경 -> 좀더 리펙토링이 필요해 보임 
- back-message api의 message index 를 요청하는 쿼리문 수정하여 삭제 되지 않은 메시지를 찾을 수 있도록 수정함. 
<br><br><br>

FIX: message bug

---

src/main/java/peer/backend/controller/dnd/DnDController.java
src/main/java/peer/backend/controller/dnd/DnDSubController.java
src/main/java/peer/backend/dto/dnd/RequestDnDDTO.java
src/main/java/peer/backend/dto/dndSub/CalendarEventDTO.java
src/main/java/peer/backend/dto/dndSub/DeleteTargetDTO.java
src/main/java/peer/backend/dto/dndSub/MemberDTO.java
src/main/java/peer/backend/service/dnd/DnDService.java
src/main/java/peer/backend/service/dnd/DnDSubService.java

- 임시 컨트롤러 작업 완료
- 위젯 이벤트에 대한 CRUD 완성
- 임시로 이벤트가 등록되었는지 여부 파악을 위한 전체 리스트 보여주는 API
- Redis 를 적용하여 DB 접근 최소화 적용
- 고유 이벤트에 대해서 임시로 HashSet 을 적용하여 처리함
- 알람 이벤트 컨트롤러가 아직임, 이벤트 알람이 가진 않음
<br><br><br>

531 refactor dnd module api url edit and enhancement

---

src/main/java/peer/backend/controller/AdminController.java
src/main/java/peer/backend/dto/KeywordRequest.java
src/main/java/peer/backend/dto/team/TeamDefaultResponse.java
src/main/java/peer/backend/dto/user/UserDefaultResponse.java
src/main/java/peer/backend/repository/team/TeamRepository.java
src/main/java/peer/backend/repository/user/UserRepository.java
src/main/java/peer/backend/service/UserService.java
src/main/java/peer/backend/service/team/TeamService.java

어드민 알림 관리 페이지에서 사용하기 위한 유저, 팀 기본 정보 리스트와 닉네임을 통한 유저 검색, 팀 이름 or 팀장 닉네임을 통한 팀 검색을 구현하였습니다.
#537 
- 유저 기본 정보 리스트
- https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=48564436
- 닉네임으로 유저 기본 정보 검색
- https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=48565636
- 팀 기본 정보 리스트
- https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=48566162
- 팀 명 or 팀장 닉네임으로 팀 기본 정보 검색
- https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=48566492
<br><br><br>

[FEATURE] 어드민 알림 파트 유저, 팀 리스트, 검색 API 개발

---

src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
src/main/java/peer/backend/dto/team/TeamApplicantListDto.java
src/main/java/peer/backend/dto/team/TeamSettingDto.java
src/main/java/peer/backend/entity/team/Team.java
src/main/java/peer/backend/entity/team/TeamUser.java
src/main/java/peer/backend/entity/team/TeamUserJob.java
src/main/java/peer/backend/repository/team/TeamUserJobRepository.java
src/main/java/peer/backend/repository/team/TeamUserRepository.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java
src/main/java/peer/backend/service/team/TeamService.java

* team Member의 다중 신청 및 관리를 위하여 teamUser에 Status 추가
* team 생성시 type이 study인 경우 STUDY로 teamJob을 STUDY로 생성하여 신청자를 관리
* type이 study인 팀에 신청시 teamUserJob을 STUDY인 teamJob으로 연결하여 생성
* team setting값 조회시 approve된 멤버만 포함
* 다중신청을 위해 answers는 teamUserJob쪽으로 이동
* 기타 관련 마이너한 수정사항
추후 로직 리팩토링 필요할 듯...
코드스멜 엄청날 것 같아서 두려움
<br><br><br>

[Hotfix] team memeber handling

---

.github/workflows/test_ci_cd.yml

풀 인스턴스기 때문에 돌아가는 데이터베이스 컨테이너를 삭제하는 로직을 제거 했습니다.
원래 백엔드 전용 클라우드에서 컨테이너를 전부 지우는 행위를 대체하는 방법을 강구해야 함.
<br><br><br>

[Fix] : fix test_ci_cd.yml file #538

---

src/main/java/peer/backend/controller/team/TeamController.java
src/main/java/peer/backend/repository/team/TeamUserRepository.java
src/main/java/peer/backend/service/team/TeamService.java

- 실제 유저가 APPROVED 되어 있는가 확인하는 validation checker 메서드를 추가하였습니다. 
- `팀 메인 페이지에서 팀 정보 불러오기` API에 해당 메서드를 적용하여, APPROVED 되지 않으면 데이터를 전달하지 않는 것으로 수정
<br><br><br>
- Postman 을 통해 401이 정상적으로 나오는지 점검 완료

FIX: getTeamInfo API add validation checker

---

src/main/java/peer/backend/annotation/CustomSize.java
src/main/java/peer/backend/annotation/OnlyEngKorNum.java
src/main/java/peer/backend/controller/profile/ProfileController.java
src/main/java/peer/backend/dto/profile/request/EditProfileRequest.java
src/main/java/peer/backend/dto/profile/response/NicknameResponse.java
src/main/java/peer/backend/validator/LineBreakNormalizerValidator.java
src/main/java/peer/backend/validator/OnlyEngKorNumValidator.java

- RestAPI 에서 사용하는 문자열 처리 방식은 ASCI 가 아닌 unicode 방식이다. 
- 그리고 개행문자의 경우 특수하게도 보여지기엔 한 글자로 처리 되지만 내부적으로 2글자로 처리 된다. 따라서 기존의 유효성 검사 방식으로는 안된다. 이에 이를 따로 파악하는 유효성 검사도구를 만들어야 한다. 
- 그렇기에 다양한 방법을 고려하다가 커스텀 어노테이션 쪽으로 확정을 잡음. 
- 기존에 사용하던 유효성 검사는 삭제함. 
- CustomSize 어노테이션 생성 및 Validator 생성 
- 닉네임 쪽도 해당 관련하여 영어, 숫자, 한글만 들어갈 수 있도록 하였으며 커스텀 어노테이션 적용 완료
- 닉네임 중복 검사 쪽 유효성 검사 추가 
<br><br><br>
실제 서비스로 테스트 완료

FIX: profile input error

---

src/main/java/peer/backend/controller/team/TeamPageController.java
src/main/java/peer/backend/repository/board/team/PostRepository.java

page 시작은 디폴트가 0,
1부터 시작하면 클라이언트 작업에 혼선을 예방 기대
포스트 출력이 최신순으로 반환되어야 해서 누락된 로직을 교정하였습니다.
<br><br><br>

[Fix] : startWithPageNum one and posts order adding desc #608

---

src/main/java/peer/backend/config/SecurityConfig.java
src/main/java/peer/backend/controller/board/ShowcaseController.java
src/main/java/peer/backend/dto/board/team/BoardCreateRequest.java
src/main/java/peer/backend/dto/board/team/PostLinkResponse.java
src/main/java/peer/backend/dto/board/team/ShowcaseCreateDto.java
src/main/java/peer/backend/dto/board/team/ShowcaseResponse.java
src/main/java/peer/backend/dto/board/team/ShowcaseWriteResponse.java
src/main/java/peer/backend/dto/user/UserShowcaseResponse.java
src/main/java/peer/backend/entity/board/team/Post.java
src/main/java/peer/backend/entity/board/team/PostFile.java
src/main/java/peer/backend/entity/board/team/PostLink.java
src/main/java/peer/backend/entity/team/Team.java
src/main/java/peer/backend/repository/board/team/PostRepository.java
src/main/java/peer/backend/service/board/team/BoardService.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java

* showcase api 중 getList, getDetail, getTeamInfo, doLike, doFavorite, create 를 구현하였습니다.
* getList와 getDetail은 토큰 없이 조회가 가능해야 해서 security config에 해당 endpoint를 permit.ALL로 등록하였습니다.
* create와 getTeamInfo에서는 팀의 리더 여부를 검사합니다.
* create시에는 showcase타입의 board를 생성하고 post를 생성합니다.
* 나머지 댓글 관련 기능과 수정 삭제 기능은 따로 브랜치를 생성하여 작업합니다.
<br><br><br>
postman

[Feat] showcase api

---

src/main/java/peer/backend/controller/board/BoardController.java
src/main/java/peer/backend/controller/board/ShowcaseController.java
src/main/java/peer/backend/dto/board/team/ShowcaseUpdateDto.java
src/main/java/peer/backend/entity/board/team/Post.java
src/main/java/peer/backend/entity/board/team/PostLink.java
src/main/java/peer/backend/service/board/team/BoardService.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java

showcase의 delete, update api 구현
답글 api는 post 답글 api 활용
<br><br><br>

[Feat] showcase_delete,update

---

src/main/java/peer/backend/dto/privateinfo/enums/PrivateActions.java
src/main/java/peer/backend/dto/profile/request/ChangePasswordRequest.java
src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
src/main/java/peer/backend/dto/security/UserInfo.java
src/main/java/peer/backend/service/PrivateInfoWrappingService.java

- 유효성 검사 및 테스트를 통해 정상 작동 여부까지 확인 완료 되었습니다. 
- 유효성 검사의 방식은 자동 생성 생성자가 아닌 수동으로 제작하는 방식으로 하며, 일단은 기존의 유효성 검사 설정된 것들을 수동으로 넣고 Exception 처리 하였습니다. 
<br><br><br>

[FEAT] private info sealing feature 5

---

src/main/java/peer/backend/dto/board/team/ShowcaseUpdateDto.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java
src/test/java/peer/backend/board/ShowcaseServiceTest.java

- post 엔티티 내의 image 필드에서 postFiles의 첫번째 이미지를 불러오도록 변경
- showcase update Request의 linklist필드가 nullable하도록 수정
<br><br><br>

[Hotfix] #675 이미지 null로 보내지는 현상 수정

---

src/main/java/peer/backend/controller/team/TeamPageController.java
src/main/java/peer/backend/dto/board/team/PostNoticeReq.java
src/main/java/peer/backend/repository/board/team/BoardRepository.java
src/main/java/peer/backend/service/board/team/BoardService.java
src/main/java/peer/backend/service/teampage/TeamPageService.java

게시판 간편 목록에서 공지사항 게시판까지 전달되는 것을
일반 게시판만 불러오도록 수정.
프론트에서 게시판 아이디를 가지고 있지 않기 때문에,
보드 아이디에서 팀 아이디로 변경.
팀 아이디를 통해 공지사항 게시판을 찾고 글 작성을 하도록 코드 수정.
<br><br><br>

736 hotfix board

---

src/main/java/peer/backend/config/SecurityConfig.java
src/main/java/peer/backend/controller/board/BoardController.java
src/main/java/peer/backend/controller/board/ShowcaseController.java
src/main/java/peer/backend/controller/team/TeamPageController.java
src/main/java/peer/backend/dto/board/team/PostCommentListResponse.java
src/main/java/peer/backend/service/board/team/BoardService.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java

* 게시판 댓글 조회, 작성 권한이 달라 showcaseController에 comment crud 컨트롤러 추가
* 각 서비스 로직에 boardtype검사로 게시판 종류에 따른 권한 검사 추가
*  showcase의 댓글을 조회할 수 있도록 security config 필터체인에 추가
* controller의존성을 줄이기 위해 Authentication 파라미터를 User로 변경
<br><br><br>

[Hotfix] showcase comment without token

---

src/main/java/peer/backend/config/SecurityConfig.java
src/main/java/peer/backend/controller/board/RecruitController.java
src/main/java/peer/backend/dto/board/recruit/RecruitFavoriteResponse.java
src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java

* boolean 배열로 반환하던 내용을 RecruitFavoriteResponse 안에 recruit_id와 함께 담아서 반환
* 메인페이지 RecruitList 조회시 favorite의 boolean 값 추가
* favorite 단건 조회 api 추가
<br><br><br>

[Hotfix] main page favorite feature

---

src/main/java/peer/backend/config/RedisRepositoryConfig.java

1. redis config 가 담긴yml 파일의 위치를 spring,data.~ 으로 이동 
2. redis config 가 그냥 Redis config factory  객체를 바로 직결하는 것에서, 객체를 만들고 설정을 불러와 connection 하는 구조로 변경 
<br><br><br>

FIX: redis connection settings

---

src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
src/main/java/peer/backend/entity/board/recruit/Recruit.java
src/main/java/peer/backend/entity/team/Team.java

* team의 name에 unique 속성때문에 update 실패 -> 정책상 unique 속성 삭제로 결정
* 팀 엔티티에서 name에 unique 속성 삭제 후 db에서 unique로 인한 키 설정 수동 삭제
+ 잃어버린 null 에러 처리
<br><br><br>

[Hotfix] update recruit

---

src/main/java/peer/backend/controller/board/RecruitController.java
src/main/java/peer/backend/controller/board/ShowcaseController.java
src/main/java/peer/backend/controller/object/ObjectController.java
src/main/java/peer/backend/entity/board/recruit/Recruit.java
src/main/java/peer/backend/entity/board/recruit/RecruitFile.java
src/main/java/peer/backend/entity/board/team/Post.java
src/main/java/peer/backend/entity/board/team/PostComment.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java
src/main/java/peer/backend/service/board/team/BoardService.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java
src/main/java/peer/backend/service/file/ObjectService.java

* ObjectController -> object storage 관리를 위해 filepath를 root/editor/userid로 변경
* ObjectService -> 마크다운 본문에서 image url을 추출하는 extractContentImage 메소드 추가
* recruit, post, showcase의 create, update, delete에 마크다운의 이미지를 엔티티로 생성, 삭제하는 로직 추가
<br><br><br>

[Hotfix] toast editor foldername and content process

---

src/main/java/peer/backend/entity/board/recruit/Recruit.java

모집글 업데이트시 기존 태그가 삭제되지 않고 남아서 중복 생성되는 것을 방지하기 위해
Recruit 엔티티의 RecruitTags에 orphanRemoval=true 옵션 추가
<br><br><br>

[Hotfix] add orphanRemoveal=true to RecruitTags

---

src/main/java/peer/backend/service/MemberService.java

- 임시 비밀번호 발급 시 기존 비밀 번호 전략에서 랜덤한 문자열을 만들 때 영어 대문자, 소문자, 숫자를 한 줄로 세우고 랜덤하게 값을 도출함.
- 이때 확률적으로 숫자, 소문자, 대문자 중 하나라도 빠지면 비밀번호 변경 전략에 저촉되어 비밀번호 변경이 안됨.
- 이에 세가지 경우를 다 쪼개서 무조건, 3가지 타입 + 특수문자까지 다 들어갈 수 있도록 전략 수정함 
<br><br><br>

fix : temporary password problem

---

src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java

[변경 사항 모집글 생성시 본문 글자 제한을 20000(2만)자로 조정
<br><br><br>

[Hotfix] 1.0.2 adjust content size for creating recruit #807

---

src/main/java/peer/backend/dto/security/UserInfo.java
src/main/java/peer/backend/entity/user/User.java

- User 객체에 `activated` 항목을 추가하였습니다. 해당 항목은 user 객체가 데모 내지는 유령 회원인 경우 등 검색이 안되어야 하며 메시지 검색 리스트 중에도 나타나면 안되기 때문입니다. 향후에는 검색 보안 부분에서 취약한 부분 개선을 해나갈 것입니다. 
<br><br><br>

FEAT : add user attribute activated for checking is valid or not

---

src/main/java/peer/backend/controller/profile/ProfileController.java
src/main/java/peer/backend/service/message/MessageMainService.java
src/main/java/peer/backend/service/profile/ProfileService.java

- 메시지를 전달할 때 읽지 않은 경우 그 숫자를 표시해주는 기능을 넣었으나, 해당 기능이 프로필에서 보낼 때 정상적이지 않게 숫자가 카운팅됨.
- 이에 수정함 
---
- 스킬 태그 추가 수정으로 특수문자 변환되서 들어오는 값을 인코딩하여 수정하는 메소드 추가하여 테스트까지 마무리
<br><br><br>

Fix message numbering failed and Add skill tag decoder 

---

src/main/java/peer/backend/entity/board/recruit/Recruit.java
src/main/java/peer/backend/entity/board/recruit/RecruitFile.java
src/main/java/peer/backend/entity/board/team/Post.java
src/main/java/peer/backend/entity/board/team/PostFile.java
src/main/java/peer/backend/entity/team/Team.java
src/main/java/peer/backend/entity/user/User.java

team, profile, recruit, post의 이미지 url 필드들을
columnDefinition="TEXT"로 수정
테스트 db 및 main db의 type은 수동으로 수정합니다.
<br><br><br>

Hotfix 1.0.2 increase size of thumbnail image field in recruit

---

src/main/java/peer/backend/config/jwt/JwtFilter.java
src/main/java/peer/backend/config/jwt/TokenProvider.java

어드민 로그인을 하고 남아있는 어드민 토큰이 일반 요청에서 Authentication으로 들어가서 type cast 에러를 나던 문제를 수정하였습니다.
<br><br><br>

[FIX] 어드민 토큰이 일반 요청들을 방해하던 에러 수정

---

src/main/java/peer/backend/dto/user/UserShowcaseResponse.java
src/main/java/peer/backend/service/board/recruit/HitchHikingService.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java

히치하이킹 리스트 반환시 content에서 이미지 태그를 제거합니다.
쇼케이스 리스트 반환시 content에서 이미지 태그를 제거합니다.
쇼케이스 반환시 member에 id 필드를 추가합니다.
<br><br><br>

[Hotfix] 1.0.2 exclude image url from hitch content

---

src/main/java/peer/backend/aspect/RequestLoggingAspect.java

게시글 종류의 요청의 경우 Respons 로깅에 result를 표현할 경우 로그가 너무 비대해져서 Response 로깅을 삭제하고 소요시간을 Request 로깅에 넣도록하고 항상 Request 로그를 찍도록 수정하였습니다.
<br><br><br>

[REFACTOR] Request 로깅 수정

---

src/main/java/peer/backend/dto/team/TeamApplyDataDTO.java
src/main/java/peer/backend/entity/board/recruit/Recruit.java
src/main/java/peer/backend/repository/team/TeamRepository.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java

- recruit  관련하여 유효성 검사 추가함. 프론트 에서도 막았으나...
1) 모집글 상태 확인하여 완료 여부 판단하도록함 
2) 모집글 작성된 팀, 팀유저, 팀유저잡을 조인하여 전체 인원수, 확정된 멤버수, 대기중인 멤버수를 파악하여 에러 유효성 검사하는 부분 추가함 해당 부분 활용하면 복잡하지 않게 현재 팀의 상태 파악이 용이해짐 
<br><br><br>

FIX: recruit validation check added

---

src/main/java/peer/backend/repository/team/TeamUserRepository.java

물론이지 채
생성한 본인은 팀 유저 상태가 Approved 기 때문에 본인만 남은 경우 삭제할 수가 없던 문제 수정.
나를 포함해서로 +1 로직 변경.
<br><br><br>

[Fix] : 모집글에서 홀로 남아있는 외로운 섬 하나 새들의 고향 #848

---

src/main/java/peer/backend/dto/board/team/PostCommentListResponse.java

게시물 댓글 조회시 authorId 필드를 추가합니다.
존재하지 않는 유저의 경우 authorId는 -1을 반환합니다.
시간이 없어 간단하게 추가할 수 있는 방식으로 작업되었습니다.
추후 hyeongki님이 작업하신 어노테이션으로 유저 유효성 검사가 수정될 필요가 있습니다.
<br><br><br>

[hotfix] add-authorId-to-PostCommentListResponse

---

src/main/java/peer/backend/controller/object/ObjectController.java
src/main/java/peer/backend/dto/announcement/AboutAnnouncementResponse.java
src/main/java/peer/backend/dto/announcement/AnnouncementListResponse.java
src/main/java/peer/backend/dto/announcement/AnnouncementResponse.java
src/main/java/peer/backend/dto/announcement/CreateAnnouncementRequest.java
src/main/java/peer/backend/dto/announcement/UpdateAnnouncementRequest.java
src/main/java/peer/backend/entity/announcement/Announcement.java
src/main/java/peer/backend/service/AnnouncementService.java

1. 토스트 에디터 이미지 업로드에 매핑 url을 추가하였습니다(어드민 공지사항에서 어드민 토큰으로도 API 사용이 가능하게끔)
2. 공지사항 쪽에 이미지 필드들 및 로직을 제거하였습니다.
<br><br><br>

[REFACTOR] 어드민 파트 짜잘 수정

---

src/main/java/peer/backend/controller/board/RecruitController.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java
src/main/java/peer/backend/service/team/TeamService.java

물론이지 호주청정우
컨트롤러에서 토큰을 사용하지 않아 추가.
조건에 부합되는 ( 모집 완료가 아닌, 팀 승인을 받은 멤버가 자신 제외 존재하지 않는 경우 )
그가 속한 해당 팀에 관련된 데이터베이스 연관 테이블 또한 삭제하도록 수정.
( 팀-유저, 팀-역할 ), 그 뒤로 모집글을 삭제.
지금은 작성자만 권한 부여.
편집 요청과 같이 AuthorCheck 사용
대신 작성자가 아닌 회원이 삭제 요청할 때
게시글 작성자만 수정할 수 있습니다. 라는 메시지 반환
<br><br><br>

[Fix] : 준비됐지 임전윤채 #848

---

src/main/java/peer/backend/controller/board/RecruitController.java
src/main/java/peer/backend/controller/board/ShowcaseController.java
src/main/java/peer/backend/repository/team/TeamUserRepository.java
src/main/java/peer/backend/repository/user/UserRepository.java
src/main/java/peer/backend/service/board/recruit/RecruitService.java
src/main/java/peer/backend/service/board/team/ShowcaseService.java
src/main/java/peer/backend/service/noti/NotificationCreationService.java
src/main/java/peer/backend/service/team/TeamService.java

1. 팀 쪽 권한 및 상태에 따라 알림이 전달되어야 하는데, 그렇게 되지 못한 점 발견
2. 쇼케이스 쪽 DTO 잘못되어 있으나, 그것을 수정하지 않은체 진행한 것 발견함.팀ID가 전달되지 않아, 대상이 비정상적으로 되어 알림 이벤트가 뜨지 않는 문제 발견
3. 멘트가 중의적이거나 일관적이지 않은 문제들 
- 알림 쪽 DB에 필요한 값들 수정하는 JPQL에 @Modifying 어노테이션 추가 
- 쪽지 전달 관련 알림 전체 수정
- 회원가입 시 나오는 문구 수정
- 팀 전반 알림 위치, 알림 관련 로직 수정 / 팀원 탐색 메소드에 대해 팀 상태 조건 추가 
- 모집글, 쇼케이스 쪽 관련 댓글, 좋아요 등에서 로직에 맞춰 알림이 갈 수 있도록 수정함. 
<br><br><br>
- 전체 테스트 사이트를 통해 직접 진행하여 작동여부 파악 완료

Hotfix notification bugs

---

src/main/java/peer/backend/config/SecurityConfig.java
src/main/java/peer/backend/controller/board/JobController.java
src/main/java/peer/backend/dto/board/Job/JobListResponse.java
src/main/java/peer/backend/dto/board/Job/JobResponse.java
src/main/java/peer/backend/entity/board/team/enums/BoardType.java
src/main/java/peer/backend/repository/board/team/PostRepository.java
src/main/java/peer/backend/service/board/Job/JobService.java

채용공고를 위한 getJob, getJobList 두가지 api를 구현
* controller, service, dto 추가
* BoardType enum에 job type 추가
* PostRepository에 boardtype으로 페이지네이션 추가
* security config의 필터체인에 해당 api의 GET Method를 전체 공개로 설정
* 해당 기능은 admin에서 채용공고를 올리고 내리는 기능이 없이 수동으로 게시물을 작성하도록 하였음.
* 따라서 추후 admin 기능으로 개발이 필요함.
<br><br><br>

feat:add-getJob-getJobList
