- backend/src/main/java/peer/backend/controller/UserPushKeywordController.java
- backend/src/main/java/peer/backend/dto/KeywordDto.java
- backend/src/main/java/peer/backend/entity/user/UserPushKeyword.java
- backend/src/main/java/peer/backend/repository/user/UserPushKeywordRepository.java
- backend/src/main/java/peer/backend/service/UserPushKeywordService.java
- backend/src/test/java/peer/backend/keyword/UserPushKeywordRepositoryTest.java
- backend/src/test/java/peer/backend/keyword/UserPushKeywordServiceTest.java
C-MYPAGE-29 ~ C-MYPAGE-31
알림 키워드 CRUD, 테스트를 작성하였습니다.
<br><br><br>
UserPushKeyword 레포지토리에 대한 테스트, UserPushKeyword 서비스에 대한 테스트 모두 통과하였습니다.
> [feat] 알림 키워드 구현

- backend/build.gradle
- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/controller/MemberController.java
- backend/src/main/java/peer/backend/dto/Message.java
- backend/src/main/java/peer/backend/dto/UserInfo.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
- backend/src/main/java/peer/backend/repository/user/UserRepository.java
- backend/src/main/java/peer/backend/service/MemberService.java
- backend/src/main/java/peer/backend/service/OAuthService.java
- backend/src/main/java/peer/backend/service/SessionService.java
- backend/src/main/resources/application.yml
B-INFO-01 기본 기능(중복 이메일 체크, 중복 닉네임 체크, 회원가입) 추가했습니다.
<br><br><br>
우선 포스트맨에서 정상적으로 동작하는 것을 확인했습니다.
> feat : B-INFO-01

- README.md
메인 readme.md 수정 커밋을 시큐리티 브랜치와 통일
<br><br><br>
> [DOCS]: pr convention modify merge main to peer-security

- backend/src/main/java/peer/backend/BackendApplication.java
- backend/src/main/java/peer/backend/entity/composite/TeamUserPK.java
- backend/src/main/java/peer/backend/entity/composite/UserAchievementPK.java
- backend/src/main/java/peer/backend/entity/team/Team.java
- backend/src/main/java/peer/backend/entity/team/TeamUser.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamMemberStatus.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamOperationFormat.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamStatus.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamType.java
- backend/src/main/java/peer/backend/entity/user/InterestedProject.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/repository/team/TeamRepository.java
- backend/src/main/java/peer/backend/repository/team/TeamUserRepository.java
- backend/src/main/java/peer/backend/repository/user/InterestedProjectRepository.java
- backend/src/main/resources/application.yml
- backend/src/test/java/peer/backend/intersted/InterestedProjectRepositoryTest.java
- backend/src/test/java/peer/backend/team/TeamRepositoryTest.java
- backend/src/test/java/peer/backend/teamuser/TeamUserRepositoryTest.java
Team과 관련된 테이블들의 엔티티 및 레포지토리 테스트를 작성하였습니다.
<br><br><br>
레포지토리에 필요한 동작들 모두 테스트 통과하였습니다.
> [FEATURE] Team Entity & Repository Test #7

- backend/build.gradle
- backend/src/main/java/peer/backend/config/CorsConfig.java
- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/config/jwt/JwtFilter.java
- backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
- backend/src/main/java/peer/backend/controller/LoginController.java
- backend/src/main/java/peer/backend/dto/request/UserLoginRequest.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/repository/user/UserRepository.java
- backend/src/main/java/peer/backend/service/LoginService.java
- backend/src/main/resources/application.yml
로그인시 토큰발급을 구현했습니다
<br><br><br>
> [Feat] C-SIGN-01 Peer security

- backend/build.gradle
- backend/src/main/java/peer/backend/controller/MemberController.java
- backend/src/main/java/peer/backend/dto/EmailMessage.java
- backend/src/main/java/peer/backend/dto/request/EmailAddress.java
- backend/src/main/java/peer/backend/service/EmailAuthService.java
- backend/src/main/resources/application.yml
- backend/src/test/java/peer/backend/BackendApplicationTests.java
회원가입시, 이메일 인증코드 전송과 이메일 인증코드 확인 기능을 추가했습니다.
<br><br><br>
JUnit 테스트 결과 정상적으로 동작합니다.
> [feat] B-INFO-01 email authentication

- backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
- backend/src/test/java/peer/backend/BackendApplicationTests.java
PrincipalDetails 클래스에서 User의 정보를 가져오는 Getter들을 추가했습니다.
<br><br><br>
JUnit 테스트 시, 정상적으로 동작합니다.
> [feat] add PrincipalDetails User getter

- backend/src/test/java/peer/backend/team/InterestedServiceTest.java
- backend/src/test/java/peer/backend/team/TeamServiceTest.java
테스트들 중 잘못된 DisplayName을 가진 것들을 수정하였습니다.
<br><br><br>
> [Fix] 테스트 잘못된 DisplayName들 수정

- .gitignore
- backend/build.gradle
- backend/src/main/java/peer/backend/annotation/ValidEnum.java
- backend/src/main/java/peer/backend/aspect/RequestLoggingAspect.java
- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/UpdateTeamRequest.java
- backend/src/main/java/peer/backend/validator/EnumValidator.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/log4j2/log4j2.xml
로깅 프레임워크 log4j2 쓰도록 수정했고 모든 API 콜에 로그 남도록 Aspect 하나 작성했습니다.
<br><br><br>
로그 잘 남고 Aspect도 잘 작동하고 파일 롤링도 잘 됩니다.
> [Feature] 로깅 설정 및 Controller Loggin Aspect

- README.md
- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamMemberKickRequest.java
- backend/src/main/java/peer/backend/repository/team/TeamUserRepository.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 수정 페이지에서 유저를 추방하기위한 API를 구현했습니다.
<br><br><br>
잘 통과하였습니다.
> [Feature] 팀 수정 페이지에서 유저 추방 API 구현

- backend/src/main/java/peer/backend/dto/security/UserInfo.java
- backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
- backend/src/main/resources/application.yml
- backend/src/test/java/peer/backend/File/ProfileImageServiceTest.java
- backend/src/test/java/peer/backend/config/jwt/TokenProviderTest.java
- backend/src/test/java/peer/backend/service/LoginServiceTest.java
머지 이후 에러나는 부분 수정하였습니다.
<br><br><br>
> [Fix] merge after error fix

- backend/src/test/java/peer/backend/File/ProfileImageServiceTest.java
donothing 사용
verify로 호출 여부만 확인
assert로 user정보 변경 확인
<br><br><br>
통과
> [Test] 프로필 이미지 삭제 테스트 코드 수정

- backend/src/main/java/peer/backend/controller/LoginController.java
- backend/src/main/java/peer/backend/dto/security/UserInfo.java
- backend/src/main/java/peer/backend/dto/security/request/ToReissueTokens.java
- backend/src/main/java/peer/backend/dto/security/request/UserLoginRequest.java
- backend/src/main/java/peer/backend/entity/user/RefreshToken.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/resources/application.yml
- backend/src/test/java/peer/backend/service/LoginServiceTest.java
main 브랜치로 merge한 이후 security에서 일어나는 오류들을 수정했습니다.
<br><br><br>
Postman으로 정상작동하는 것을 확인했습니다.
> [Fix] security errors

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamListResponse.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamStatus.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
- backend/src/test/java/peer/backend/team/TeamControllerTest.java
- backend/src/test/java/peer/backend/team/TeamServiceTest.java
팀 리스트 api에서 상태별로 팀을 가져올 수 있습니다. 피그마에 맞게 dto에 요소를 추가했습니다
<br><br><br>
Controller, Service Test 통과
> [Feat]: Enhance team list with additional details and filtering by team status

- backend/src/main/java/peer/backend/config/JwtSecurityConfig.java
- backend/src/main/java/peer/backend/config/RedisRepositoryConfig.java
- backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
- backend/src/main/java/peer/backend/dto/security/UserInfo.java
- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
- backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
- backend/src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
- backend/src/main/java/peer/backend/service/MemberService.java
- backend/src/main/java/peer/backend/service/SocialLoginService.java
- backend/src/test/java/peer/backend/BackendApplicationTests.java
소셜 로그인 후 회원가입시 자동 연동까지 구현하였습니다.
<br><br><br>
> [Feature] OAuth

- backend/src/main/java/peer/backend/controller/MemberController.java
- backend/src/main/java/peer/backend/dto/security/request/EmailAddress.java
- backend/src/main/java/peer/backend/dto/security/request/EmailCode.java
- backend/src/main/java/peer/backend/service/EmailAuthService.java
- backend/src/main/java/peer/backend/service/MemberService.java
- backend/src/test/java/peer/backend/service/EmailAuthServiceTest.java
- 이메일 중복 체크
- 인증 코드 레디스 저장 & 검증
<br><br><br>
- emailCodeVerificationTest: ok
> [FEATURE] 회원가입 관련 추가 기능

- backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
- backend/src/main/java/peer/backend/dto/profile/PasswordRequest.java
- backend/src/main/java/peer/backend/dto/profile/PersonalInfoResponse.java
- backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
- backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
- backend/src/test/java/peer/backend/service/profile/PersonalInfoServiceTest.java
C-MYPAGE-09에 해당하는, 사용자 개인정보 조회 API를 구현했습니다.
C-MYPAGE-11에 해당하는, 비밀번호 변경 API를 구현했습니다.
<br><br><br>
단위 테스트를 진행했고, Postman으로 확인했습니다.
> [FEATURE] 사용자 개인정보 조회 API, 비밀번호 변경 API

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/dto/profile/EditProfileDTO.java
- backend/src/main/java/peer/backend/dto/profile/MyProfileResponse.java
- backend/src/main/java/peer/backend/dto/profile/UserLinkDTO.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/test/java/peer/backend/service/profile/ProfileServiceTest.java
- 사용자 프로필을 조회하는 API를 구현했습니다.
<br><br><br>
- 비즈니스로직 단위 테스트 통과했고, Postman으로 확인했습니다.
> [FEATURE] 사용자 프로필 조회 API

- backend/Dockerfile
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.yml
배포 관련하여 application.yml 및 Dockerfile을 수정하였습니다.
<br><br><br>
> [CHORE] Deploy

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/controller/ExcelController.java
- backend/src/main/java/peer/backend/controller/MemberController.java
- backend/src/main/java/peer/backend/dto/security/UserInfo.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/entity/user/enums/Role.java
- backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
- backend/src/main/java/peer/backend/service/MemberService.java
- backend/src/test/java/peer/backend/keyword/UserPushKeywordRepositoryTest.java
- backend/src/test/java/peer/backend/team/InterestedProjectRepositoryTest.java
- backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
- 유저 탈퇴(일단 단순 엔티티 삭제, 2스텝에 정책에 따라 수정 필요)
- 유저 권한 추가(ROLE_USER, ROLE_ADMIN)
<br><br><br>
단순 구현이라 테스트는 제외하였습니다.
> [FEATURE] 유저 관련 추가 구현

- backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
- backend/src/main/java/peer/backend/dto/profile/FavoritePage.java
- backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- backend/src/test/java/peer/backend/profile/FavoriteControllerTest.java
- backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
- 관심 목록을 조회하는 API를 구현했습니다.
- 관심 목록을 전부 삭제하는 API를 구현했습니다.
<br><br><br>
- 서비스는 단위 테스트 진행했고, 컨트롤러는 데이터 베이스에 직접 데이터를 넣어서 Postman으로 확인했습니다.
> [FEATURE] Profile module - Favorite recruit API

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/test/java/peer/backend/board/RecruitServiceTest.java
모집게시글 검색 기능을 위한 controller, service 추가
<br><br><br>
postman 테스트
> [FEATURE] #129 모집게시글 검색 기능

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitFavorite.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/test/java/peer/backend/board/RecruitServiceTest.java
모집게시글 담기 기능 추가(controller, service 추가, RecruitFavorite 엔티티 수정)
<br><br><br>
postman
> [FEATURE] #132 모집게시글 담기 기능

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitRequest.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitFavorite.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/test/java/peer/backend/board/RecruitServiceTest.java
모집게시글 검색 api 호출시 @modelattribute 어노테이션 동작을 위하여 옵션으로 request 변수명을 직접 명시하였습니다.
<br><br><br>
postman
> [Fix] #136 모집게시글 검색 기능 param 매핑 fix

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitInterviewDto.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListRequestDTO.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitRoleDTO.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitApplicant.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/test/java/peer/backend/board/RecruitServiceTest.java
Recruit 상세 조회 api와 관련 기능들 추가하였습니다.
junssong님 요청으로 RecruitApplicant에 String nickname 필드를 추가하였습니다.
<br><br><br>
postman
> feature : getRecruit function and related dto

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitAnswerDto.java
- backend/src/main/java/peer/backend/repository/board/recruit/RecruitApplicantRepository.java
- backend/src/main/java/peer/backend/repository/user/UserRepository.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 세팅에서 신청자 리스트를 받을 수 있습니다.
팀 세팅에서 신청자를 승인할 수 있습니다.
팀 세팅에서 신청자를 거절할 수 있습니다.
TODO: 승인, 거절 시 알림을 보내야 합니다.
<br><br><br>
PostMan으로 테스트 완료.
> [FEATURE]: teamSetting - teamApplicants Api

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitInterviewDto.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListRequestDTO.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitRoleDTO.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitApplicant.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/test/java/peer/backend/board/RecruitServiceTest.java
Recruit 상세 조회 api와 관련 기능들 추가하였습니다.
junssong님 요청으로 RecruitApplicant에 String nickname 필드를 추가하였습니다.
<br><br><br>
postman
> 147 feature getrecruit add and related dtos

- backend/src/main/resources/application-local.yml
- backend/src/test/java/peer/backend/board/RecruitRepositoryTest.java
- backend/src/test/java/peer/backend/board/RecruitServiceTest.java
> hotfix : test commenting out, local yml create to update, filepath add.

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamApplicantListDto.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
- backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
팀 세팅 api Dto 이름 수정이 있었습니다.
3개의 api 같은 Dto를 사용하고있어서 한번에 pr하겠습니다.
<br><br><br>
PostMan 성공
> [REFACTOR]: TeamSetting Applicant's api

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/ApplyRecruitRequest.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
모집게시글의 인터뷰에 응답하여 지원하기를 눌렀을 때 RecruitApplicant를 생성합니다.
이미 지원된 경우 400에러를 반환합니다.
updateRecruit에서 불필요한 변수를 삭제(index) 마크다운 파싱 결과에 따라 썸네일이 변경될 수 있도록 수정하였습니다.
<br><br><br>
postman
> [FEATURE] #155 apply recruit add

- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- 프로필 정보 수정할 때, 파일이 비어있는지에 대한 조건문을 수정했습니다.
-  yml 파일에 프로필 이미지가 저장될 경로를 추가했습니다.
<br><br><br>
- 단위 테스트 통과했고, postman 으로 확인했습니다.
> fix: profile image check condition and add file path in yml files

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamListResponse.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 리스트 api를 수정했습니다
<br><br><br>
post 맨으로 통과했습니다
> refactor: Add authentication to team list API, simplify code

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamInfoResponse.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 메인 페이지 에서 팀 정보를 가져옵니다
<br><br><br>
```
{
"id": 2,
"name": "team2",
"teamPicturePath": null,
"status": "모집중",
"memberCount": "2 / 4",
"leaderName": "song",
"dueTo": "3",
"operationFormat": "오프라인",
"region": [
"as",
"sdf",
"asdf"
]
}
```
> feat: Implement API to fetch team information on team main page

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
400 -> 409로 수정하였습니다.
<br><br><br>
> [REAFCTOR] signup nickname return code 수정

- backend/src/main/java/peer/backend/controller/SignInController.java
Signin 관련 엔드포인트를 수정하였습니다.
<br><br><br>
> [REFACTOR] Signin refactoring

- backend/src/main/java/peer/backend/controller/SignUpController.java
- backend/src/main/java/peer/backend/service/MemberService.java
API가 수정됨에 따라 비밀번호 검증을 추가하였습니다.
<br><br><br>
> [REFACTOR] 유저 탈퇴 관련 리팩토링

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/ApplyRecruitRequest.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
모집글 작성시 태그리스트 반환,
모집글 수정시 기존 정보 로드 메소드 추가
<br><br><br>
> [FEATURE] #158 taglist write form add

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/service/MemberService.java
- signin Http Method 변경
- 소셜 로그인 회원 가입 시 에러 상황 추가
- User 닉네임, 네임 길이 수정
<br><br><br>
> [REFACTOR] signin, signup 짜잘 수정

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 메인 페이지에서 팀 멤버 리스트를 가져옵니다
<br><br><br>
postMan 성공 403 404 확인
```
[
{
"id": 1,
"name": "junsang",
"role": "LEADER"
},
{
"id": 2,
"name": "asdf",
"role": "MEMBER"
}
]
```
> [FEATURE]: Implement API to fetch teamMember list on team main page

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/repository/team/TeamUserRepository.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
TeamController Api Principal 에서 Authentication으로 변경했습니다. Service에서 isLeader 함수를 만들었습니다.
<br><br><br>
모든 api 테스트 통과
> [REFACTOR]: Change TeamController method principal to Authentication

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/controller/ExcelController.java
admin 관련 endpoint를 규칙에 맞게 수정하였습니다.
<br><br><br>
> [REFACTOR] tracking-excel endpoint modified

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/LoginService.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
https://github.com/peer-42seoul/Peer-Backend/commit/4a9dcc53199acc1e13d2ac0fd3dbe42b9e42a174
이 커밋만 해당합니다. 
sendLetterInNewWindow API 수정완료 
<br><br><br>
> 152 refactor message hotfix authentification send letter in new window

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/LoginService.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
get specific letters API 에 추가 완료 
마지막 커밋만 보시면 됩니다. 
<br><br><br>
> 152 refactor message hotfix authentification get specific letters

- backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
- backend/src/main/java/peer/backend/controller/profile/KeywordAlarmController.java
- backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- backend/src/main/java/peer/backend/service/profile/KeywordAlarmService.java
- backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
- backend/src/test/java/peer/backend/profile/KeywordAlarmServiceTest.java
- backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
- backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
- 키워드 알람 API의 Authentication 관련 코드들을 수정했습니다.
<br><br><br>
> 172 refactor all authentication keyword api

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
- Profile API의 Authentication을 활용하는 부분을 수정했습니다.
<br><br><br>
> refactor: profile api authentication

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/LoginService.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
단순 Authentication 인자만 추가하였습니다. 
맨 아래의 [FEAT: Add Authentication](https://github.com/peer-42seoul/Peer-Backend/commit/ef4a0a02d01e1ff3bd5d0d9ab46979c20e655a5c) 이 커밋만 확인하시면 됩니다. 
<br><br><br>
> 152 refactor message hotfix authentification refactor search nickname in new window

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/LoginService.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
잡다한 주석 처리 및 문서 내용 추가 
<br><br><br>
> 152 refactor message hotfix authentification chore

- backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
- backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
- backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
- backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
- 개인 정보 API의 Authentication 관련 코드들을 수정했습니다.
- 관심리스트 API의 Authentication 관련 코드들을 수정했습니다.
<br><br><br>
> 172 refactor all authentication personal favorit api

- backend/src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
- backend/src/main/java/peer/backend/dto/profile/response/UserLinkResponse.java
- backend/src/main/java/peer/backend/repository/user/UserLinkRepository.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- UserLinkResponse와 UserLinkRequest 로 DTO를 분리했습니다.
- UserLinkResponse에 id(user link id)를 추가했습니다.
<br><br><br>
> fix: get profile API

- backend/src/main/java/peer/backend/entity/team/Team.java
- backend/src/main/java/peer/backend/entity/team/TeamUser.java
팀유저 엔티티에 job String을 추가했습니다.
<br><br><br>
PostMan 통과
> feat: add teamUser entity job

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
- backend/src/main/java/peer/backend/dto/profile/response/UserLinkResponse.java
- backend/src/main/java/peer/backend/entity/user/UserLink.java
- backend/src/main/java/peer/backend/repository/user/UserLinkRepository.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- 프로필 정보 중, 링크가 등록되지 않는 문제를 해결했습니다.
<br><br><br>
> 171 fix edit link api

- backend/src/main/java/peer/backend/aspect/UserTrackingAspect.java
- backend/src/main/java/peer/backend/entity/user/SocialLogin.java
- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
- backend/src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
- backend/src/main/java/peer/backend/service/MemberService.java
- backend/src/main/java/peer/backend/service/SocialLoginService.java
- backend/src/main/java/peer/backend/service/UserService.java
- backend/src/main/resources/application-dev.yml
최초 소셜 로그인 - 회원가입 시 유저 추적 데이터에서 42 연결 여부가 true로 바뀌지 않던 문제 해결
<br><br><br>
포스트맨으로 테스트하였습니다.
> [FIX] when first social login - signup not tracking ft linking fix

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
메인리스트를 토큰 없이 불러올 수 있도록 securityFilter에 /api/v1/recruit 추가
토큰 존재 여부에 따라 isFavorit 매핑 로직 수정
<br><br><br>
postman 완료
> [FIX] #208 get main list without token

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListRequestDTO.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitRequest.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
1개의 region만 받던 것을
2개의 Region을 List로 받도록 수정함.
<br><br><br>
> FIX #207 regionList form modified

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/config/SwaggerConfig.java
- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- 스웨거 접근 불가하여 스웨거 접속 가능하도록 security 설정 추가함
- 일부 테스트 진행하면서 이슈 발생하여 이슈 파둠
<br><br><br>
> [FIX] add security setting for swagger

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitInterviewDto.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
인터뷰 리스트를 불러오는 콘트롤러와 서비스를 만들었습니다.
모집 상세글 Response에서 interviewList를 삭제하였습니다.
<br><br><br>
> FEATURE #128 getInterviewList controller, service add

- backend/src/main/java/peer/backend/entity/team/Team.java
정책변경으로 팀 엔티티의 region 세개를 nullable하게 변경합니다.
<br><br><br>
> fix: modify region fields of Team entity to be nullable

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
cors 설정에서 allow origin을 applicatio.yml의 value를 활용하도록 수정하였습니다.
<br><br><br>
> [FEAT] cors allow origin use to application.yml value

- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
- 프로필 정보를 수정하는 API에 파일 모듈을 추가했습니다.
- 테스트 코드도 그에 맞도록 수정했습니다.
- yml 파일에 프로필 이미지가 저장되는 파일 경로를 수정했습니다.
<br><br><br>
> [REFACTOR]Profile module apply file module

- backend/src/main/java/peer/backend/dto/security/UserInfo.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/exception/GlobalControllerAdvice.java
- backend/src/test/java/peer/backend/keyword/UserPushKeywordRepositoryTest.java
- backend/src/test/java/peer/backend/team/InterestedProjectRepositoryTest.java
- backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
signup Dto에 유효성 검증을 추가하였습니다!
<br><br><br>
포스트맨으로 테스트 하였습니다!
> [REFACOTR] signup dto 유효성 검증 추가 #288

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/exception/GlobalControllerAdvice.java
- backend/src/main/java/peer/backend/exception/MethodArgumentNotValidException.java
> FIX #239 security config antMatcher filter add

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> FIX #238 modify package path

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/dto/message/TargetDTO.java
- UserId Param 으로 받던것 삭제
- 하는 김에 추가로 거슬리던 Validation 어노테이션 하나 추가
- 내용 많을 줄 알았는데, 지난번에 처리 하면서 다 바꿔둬서 걍 한번에 처리 완료 ~ ~
<br><br><br>
> FIX : remove param userId

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- 세부 메시지 목록에 들어가서 쪽지 작성 및 전달 시 201 만 전달하지 않도록 수정
- Msg 객체 하나 전달
- 무한스크롤 테스트 진행함
<br><br><br>
> [REFACTOR] 242 feat api modification for response send message

- backend/src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
- 프론트와 합의한 DTO와 맞지 않아 수정했습니다. (company -> association)
- 프론트와 합의한 DTO의 타입과 맞지 않아 수정했습니다. (intorduction은 nullable 하지 않음)
- 테스트 코드 변경
<br><br><br>
> [HOTFIX] 프로필 조회 API의 DTO 변경

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamImageDto.java
- backend/src/main/java/peer/backend/dto/team/TeamInfoResponse.java
- backend/src/main/java/peer/backend/entity/team/Team.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
> [FEATURE] add team setting teamimage api

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
recruitCreate endpoint를 ""에서 "/write"로 변경
<br><br><br>
> HOTFIX : recruitCreate endpoint fix

- backend/src/main/java/peer/backend/service/file/FileService.java
string으로 들어오는 데이터를 폼데이터로 변형 후 파일을 세이브 합니다.
<br><br><br>
> refact: string to formdata and save add

- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
OAuth Redirct url을 프론트에 맞춰 수정하였습니다.
<br><br><br>
> [FIX] oauth redirect url 수정

- backend/src/main/java/peer/backend/entity/board/recruit/enums/RecruitApplicantStatus.java
- backend/src/main/java/peer/backend/entity/board/recruit/enums/RecruitInterviewType.java
- backend/src/main/java/peer/backend/entity/board/recruit/enums/RecruitStatus.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
팀 생성시 teamType과 teamOperationFormat 값을 영어로 받아오기 위하여
enum을 dto로부터 from 메소드를 사용해서 받아오던 것을 (enum).valueOf메소드를 사용하여 받아옵니다.
<br><br><br>
포스트맨 테스트
> 262 hotfix 모집게시글 검색시 type값 한글로 보내야 하는 부분 영어로 수정

- backend/src/main/java/peer/backend/exception/GlobalControllerAdvice.java
> HOTFIX #252 add errorHandler when missing request param

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
getSearchList 서비스에서 from으로 Enum 검색하는 부분 valueOf로 변경
<br><br><br>
> HOTFIX #274 Enum.from -> Enum.valueOf

- backend/src/main/resources/application-dev.yml
백엔드용 리다이렉트 도메인을 추가해서 수정하였습니다.
<br><br><br>
> [FIX] google oauth redirect url

- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- 컨트롤러에서 토큰을 받지 않도록 수정했습니다.
- 해당 컨트롤러에 접근할 수 있도록 security 파일에 설정했습니다.
<br><br><br>
> fix: get other profile not token

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- backend/src/main/java/peer/backend/entity/board/recruit/Tag.java
- backend/src/main/java/peer/backend/entity/board/recruit/TagListManager.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
Tag, TagListManager 추가
tagList 조회하는 ResponseBody들 List<TagListResponse> 사용하도록 수정
tagList 불러오는 api endpoint 수정
<br><br><br>
포스트맨
> [HOTFIX] #280 모집글 단건, 다중 조회시 taglist가 content와 color로 전달될 수 있게 수정

- backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
- backend/src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
- backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
- 패스워드 정책에 맞게 변경할 수 있도록 수정했습니다.
- 변경할 패스워드를 확인할 때 나오는 Http error code를 수정했습니다.
<br><br><br>
> fix: change Http error code and add password validation

- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
recruit 단건조회시 responseBody에 place Filed 추가
<br><br><br>
> fix : add place field when getRecruit

- backend/src/main/java/peer/backend/controller/profile/KeywordAlarmController.java
- backend/src/main/java/peer/backend/service/profile/KeywordAlarmService.java
- 구분문자에 대한 오류가 있어 수정했습니다.
- 키워드 하나만 존재할 때 삭제가 가능하도록 했습니다.
<br><br><br>
> 279 hotfix alarmkeyword delete

- backend/src/main/java/peer/backend/controller/SignUpController.java
비밀번호 검증 조건문이 잘못되어 수정하였습니다.
<br><br><br>
> [FIX] withdrawal password verification

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/dto/profile/request/EditProfileRequest.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
- boolean 값을 Boolean으로 변경했으나, form-data로부터 boolean 값을 가져오기 위해 String으로 변경했습니다.
- 이미지 저장 위치는 아직 결정난 것이 없어 그대로 유지했습니다.
<br><br><br>
> 258 hotfix profile controller and dto

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
기존에 협의했던 사항이랑 구현되있는게 달라서 refreshToken을 쿠키로 전달하게끔 수정하였습니다.
<br><br><br>
> [FIX] refresh token 쿼리스트링에서 제거하고 쿠키에 추가

- .github/workflows/random_reviewers.yml
- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- 자기 자신의 user nickname 혹은 User Email 이 검색되지 않도록 처리 완료
- git action 수정
<br><br><br>
> [HOTFIX] self searching issue

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/ApplyRecruitRequest.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
user_id를 body로 받아오던 기존 코드를 auth를 사용하도록 변경
<br><br><br>
> [HOTFIX] #309 use auth instead user_id param

- backend/src/main/java/peer/backend/service/message/MessageSubService.java
- 삭제를 한 사람과 대화를 다시 시작하게 되었을 때, 기존의 대화기록이 있는 경우, 이를 복원  시킨다.
- 단, 이때 양쪽에서 대화를 삭제 했을 경우 대화는 모두 날아가므로 삭제 된다. 
<br><br><br>
> [HOTFIX] make a method to recovery message index deleted

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/dto/message/TargetDTO.java
- backend/src/main/java/peer/backend/dto/message/TargetForDelete.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- 최초 메시지 전달 안되는 것을 수정 중에 삭제가 비정상작동을 확인하여, 작업 진행함. 
- DTO 문제였고, 향후 픽스 이후에 리팩토링 필요함(비효율적인 구조임)
<br><br><br>
> [HOTFIX] message DTO, it needs refactoring

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/dto/message/TargetDTO.java
- backend/src/main/java/peer/backend/dto/message/TargetForDelete.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- 최초 메시지 문제 발견하고 수정 중에 발견한 문제 수정 
- delete 메소드 호출 시 정상 처리 이후 getAllList 메소드를 실행시, 삭제를 요청한 message Index가 정상적으로 삭제 된걸로 반환되지 않은 문제가 발생함. 
- 문제를 조사한 결과 비동기 처리를 해놓았음에도, 이에 대해 get 을 받지 않고 처리하다보니, getAllList에서 데이터가 처리되기 전에 반환하는 것으로 확인됨. 이에 Async를 기다리는 구조로 수정함 
<br><br><br>
> [HOTFIX] bug first message failed delete method async fix

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/exception/AlreadyDeletedException.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- backend/src/main/java/peer/backend/service/message/MessageSubService.java
- backend/src/main/resources/application-dev.yml
- 총 정리 되었습니다! 무력 머지 진행합니다..! 
<br><br><br>
> 285 bug deleted message recovery strategy

- backend/src/main/java/peer/backend/controller/SignInController.java
reissue에서 refreshToken을 cookie를 사용하게끔 수정하였습니다.
<br><br><br>
> [FIX] reissue use cookie

- backend/src/main/java/peer/backend/controller/SignUpController.java
- backend/src/main/java/peer/backend/service/MemberService.java
프론트분과 협의하에 비밀번호가 틀렸을경우 403을 리턴하도록 수정하였습니다.
<br><br><br>
> [FIX] wrong password throw 403

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- 서버 환경에서 입력한 링크가 저장되지 않는 문제가 발생했지만, 로컬에서는 정상적으로 작동하는 상황
- 때문에, null이 아닌 빈 문자열로 들어오는 것이 문제인지 우선 확인하기 위해 해당 내용을 수정했습니다.
<br><br><br>
> fix: permit empty string

- backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
- backend/src/main/java/peer/backend/repository/board/recruit/RecruitFavoriteRepository.java
- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
- 관심 리스트 조회 시 사용될 타입(project, study)를 모두 대문자로 변경했습니다.
- 관심 리스트 lazy 문제를 발견해, RecruitFavoritRepository를 추가하고, 해당 인터페이스에 findAllByUserId를 추가했습니다.
<br><br><br>
> fix: change type and add recruit repository

- backend/src/main/java/peer/backend/annotation/tracking/UserWithdrawalTracking.java
- backend/src/main/java/peer/backend/aspect/UserTrackingAspect.java
- backend/src/main/java/peer/backend/mongo/entity/enums/UserTrackingStatus.java
- backend/src/main/java/peer/backend/service/ExcelService.java
- backend/src/main/java/peer/backend/service/MemberService.java
유저 탈퇴 추적 기능을 추가하였습니다.
<br><br><br>
> [FEATURE] 유저 탈퇴 추적

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- backend/src/main/java/peer/backend/service/message/MessageSubService.java
- 500 에러 해결 후, 최초 메시지 전달 부분에서 로직 확인 부분에서 문제 있음을 발견. 
- 해당부분 로직 조정으로 최초 메시지 전달 가능하게 수정 됨
<br><br><br>
> 273 bug first message failed

- backend/src/main/java/peer/backend/annotation/tracking/TeamCreateTracking.java
- backend/src/main/java/peer/backend/aspect/TeamTrackingAspect.java
- backend/src/main/java/peer/backend/mongo/entity/TeamTracking.java
- backend/src/main/java/peer/backend/mongo/repository/TeamTrackingRepository.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
Team 생성 추적 기능을 구현하였습니다.
<br><br><br>
> [FEATURE] Team Create Tracking

- backend/src/main/java/peer/backend/dto/team/TeamMemberDto.java
User Name을 NickName으로 변경합니다
<br><br><br>
성공
> fix: TeamSettingDto

- backend/src/main/java/peer/backend/dto/team/TeamSettingInfoDto.java
- backend/src/main/java/peer/backend/entity/team/Team.java
한글로 받는 json을 영어로 수정
<br><br><br>
> fix: Post TeamSettingDto

- backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
- 관심 프로젝트를 조회할 때, recruit의 tag가 변경된 점을 적용했습니다.
- postId를 recruit_id로 변경했습니다.
<br><br><br>
> fix: change postId to recruit_id and tagList

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
모집글 작성시 대표 이미지를 포함하여 모집글을 생성하기 위하여
form-data로 데이터를 받도록 수정
Controller에 RequestPart image를 추가하고 다른 필드는 ModelAttribute로 매핑
<br><br><br>
> [HOTFIX] #276 add thumbnail image when recruit created

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
메인페이지에서 모집글 리스트를 불러올 때 페이지네이션이 적용되지 않던 부분 수정
query실행시 결과에 .setPageSize, .setPage 설정 추가
<br><br><br>
> [HOTFIX] @292 메인페이지 리스트 불러오기시 페이지네이션 수정

- backend/src/main/java/peer/backend/dto/profile/FavoritePage.java
- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- backend/src/test/java/peer/backend/profile/FavoriteControllerTest.java
- backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
- 정확한 페이징을 위해 엔티티 메니저와 쿼리문을 통해 recruit를 찾는 메서드를 추가했습니다.
- 그리고 그 결과를 가지고 전송할 페이지를 잘라주는 메서드를 추가했습니다.
- 우선 테스트 코드를 모두 주석 처리 했습니다.
<br><br><br>
> 329-favorite-view-1

- backend/src/main/java/peer/backend/mongo/entity/TeamTracking.java
- backend/src/main/java/peer/backend/service/ExcelService.java
엑셀 다운로드 기능에서 팀 추적 시트를 추가하였습니다.
<br><br><br>
> [FEATURE] TeamTracking Excel Download

- backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
- 관심 리스트 전체 삭제 API 성공시 204를 반환하도록 변경했습니다.
<br><br><br>
> fix: change http code to 204

- backend/src/main/java/peer/backend/dto/profile/response/UserLinkResponse.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- 프로필 조회 시 사용되는 DTO의 link를 linkUrl로 변수명을 변경했습니다.
<br><br><br>
> refactor: change link to linkUrl

- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- 관심 리스트 전체 삭제 시, EntityManager를 이용해서 삭제를 진행하도록 변경했습니다.
<br><br><br>
> fix: deleteAllFavorite API to use entity manager

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
페이지네이션시 toIndex의 max값을 전체 리스트 넘어가지 않도록 조정
<br><br><br>
> [HOTFIX] toIndex max value adjust

- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
oauth redirect url을 수정하였습니다.
<br><br><br>
> [FIX] oauth redirect url modified

- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListRequest.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
단건 equal로 조회를 다중 in으로 조회하도록 쿼리 수정
<br><br><br>
> [HOTFIX] #338 place, status 다중 검색을 위해 쿼리 수정

- backend/src/main/java/peer/backend/service/profile/FavoriteService.java
- 관심 리스트 DTO에 recruit_id를 반환하도록 변경했습니다.
<br><br><br>
> fix: add recruit_id when view favorite recruit

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
due를 범위에서 단건 조회로 변경
<br><br><br>
> [HOTFIX] #332 due search using single value

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- backend/src/main/java/peer/backend/entity/user/UserLink.java
- backend/src/main/java/peer/backend/service/profile/ProfileService.java
- 링크를 수정할 때, 링크에 등록되어 있는 유저를 null로 지정함으로써 해제하도록 했습니다.
<br><br><br>
> fix: disassociate the user from the user link

- backend/build.gradle
- backend/src/main/java/peer/backend/config/SecurityConfig.java
- backend/src/main/java/peer/backend/config/SocketIoConfig.java
- backend/src/main/java/peer/backend/controller/socket/SocketIoServerController.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- 소켓 연결을 위한 컨트롤러 설정 완료 
- reuse Address 로 포트 재사용 가능하도록 설정 완료 
- 커넥션과 디스커넥션 인식 가능
<br><br><br>
> FEAT: socket controller is ready

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/dto/team/TeamMemberDto.java
- backend/src/main/java/peer/backend/dto/team/TeamSettingInfoDto.java
- backend/src/main/java/peer/backend/dto/team/UpdateTeamRequest.java
- backend/src/main/java/peer/backend/entity/team/Team.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamMemberStatus.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamOperationFormat.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamStatus.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamType.java
- backend/src/main/java/peer/backend/entity/team/enums/TeamUserRoleType.java
팀dto의 enum에 어노테이션을 추가했습니다.
<br><br><br>
postman 동작확인
> [Fix] 팀dto의 enum에 어노테이션을 추가했습니다.

- backend/src/main/java/peer/backend/config/SocketIoConfig.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
> WIP: socket connection port change 8081

- backend/src/main/java/peer/backend/controller/profile/ProfileController.java
- 조건문을 변경해 닉네임이 1자 이하, 8자 이상이면 400 error를 반환하도록 변경했습니다.
<br><br><br>
> 365 hotfix nickname len

- backend/src/main/java/peer/backend/controller/SignInController.java
- backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
OAuth에서 쿠키가 안구워지던 문제를 Path를 추가해서 해결하였습니다.
<br><br><br>
> [FIX] refresh cookie add path

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- port 수정 : 8080 -> 8081
- message getSpecificList 항목에 대해 상대방이 메시지를 삭제 했으면 확인하고 exception 을 throw 하는 로직추가(HTTPS.GONE)
- 그외에 비정상 접속 대비하는 로직 추가
<br><br><br>
> FEAT: Add new error handling logic

- backend/src/main/java/peer/backend/controller/socket/SocketIoServerController.java
- backend/src/main/java/peer/backend/dto/message/MsgTarget.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
- backend/src/main/java/peer/backend/service/message/MessageSubService.java
- DTO 수정, 상대방 대화 삭제 여부를 파악하는 내용추가함
- 이를통해 대화 삭제한 상대가 아닌 상대가 대화를 요청했을 때, 삭제 여부를 프론트에게 알려준다. 
<br><br><br>
> FEAT: update conversationList api

- backend/src/main/java/peer/backend/annotation/tracking/TeamUpdateTracking.java
- backend/src/main/java/peer/backend/aspect/TeamTrackingAspect.java
- backend/src/main/java/peer/backend/mongo/repository/TeamTrackingRepository.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
> [FEATURE] Team Update Tracking

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/ApplyRecruitRequest.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitInterviewDto.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitApplicant.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitInterview.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitRole.java
- backend/src/main/java/peer/backend/entity/composite/RecruitApplicantPK.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/file/FileService.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
모집글 중복 지원 가능하게 수정(같은 역할에는 지원 안됨.)
모집글 생성시 이미지를 base64encodedString으로 받음.
<br><br><br>
> 307 hotfix 모집글 중복지원 가능 작업

- backend/build.gradle
- backend/src/main/java/peer/backend/controller/temp/TempDnDController.java
- backend/src/main/java/peer/backend/dto/temp/RequestDnDDTO.java
- backend/src/main/java/peer/backend/entity/team/DataGrid.java
- backend/src/main/java/peer/backend/entity/team/Widget.java
- backend/src/main/java/peer/backend/mongo/entity/TeamDnD.java
- backend/src/main/java/peer/backend/mongo/repository/PeerLogDnDRepository.java
- backend/src/main/java/peer/backend/mongo/repository/TeamDnDRepository.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/temp/TempDnDService.java
- DnD를 위한 실험적인 레포지터리 및 컨트롤러 작성을 완성하였습니다. 
- CRUD 기능을 가지고 있으며 기본적으로 Team이 존재할 때 해당 데이터를 CRUD 해줍니다(모집글 생성-팀생성이 무조건)
- LocalDateTime 은 JAVA8 에서 JSON 직렬화, 역직렬화를 지정해줘야 DB 저장이 가능하고 그러다보니 프론트에서 해당 데이터를 정상적으로 받을 수 있는지 확인이 필요합니다(LocalDateTime이 가능한지, 아니면 List<string> 이 되어야 하는지) 
- 상세한 내용은 API 문서를 참고 바랍니다. 
<br><br><br>
> 370 2step dnd dto

- backend/src/main/java/peer/backend/dto/team/TeamSettingInfoDto.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
teamImage를 받을 때 파싱을 해서 넘겨주도록 했습니다. 이래야 프론트에서 편하다고 합니다
<br><br><br>
postman 통ㅘ
> refact: parse teamImage of TeamSettingApi

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/message/MessageMainService.java
> HOTFIX: fix error handling HTTP status number

- backend/src/main/java/peer/backend/entity/temp/Temp.java
- backend/src/main/java/peer/backend/repository/temp/TempRepository.java
- test를 위한 임시 레포지터리 입니다~~~
- 네스트 적용을 위해 일단 DEV에 머지합니다(삭제 예정)
<br><br><br>
> TEST: add testing repository and testing

- backend/src/main/resources/application-dev.yml
- 소켓 설정만 바꾸었습니다...!
- 테스팅을 위해 강제 머지...!
<br><br><br>
> ADD remote settings for socket

- backend/src/main/java/peer/backend/aspect/ActivityTrackingAspect.java
- backend/src/main/java/peer/backend/aspect/UserTrackingAspect.java
- backend/src/main/java/peer/backend/entity/user/User.java
- backend/src/main/java/peer/backend/service/MemberService.java
- backend/src/main/java/peer/backend/service/SocialLoginService.java
- backend/src/main/java/peer/backend/service/UserService.java
유저 회원가입 시 activity_tracking에 인트라 아이디를 추가하기 위해 기존 코드를 리팩토링 하였습니다.
<br><br><br>
> [REFACTOR] user registration tracking refactoring

- .gitignore
- backend/src/main/java/peer/backend/annotation/tracking/RecruitWritingTracking.java
- backend/src/main/java/peer/backend/aspect/ActivityTrackingAspect.java
- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/mongo/entity/ActivityTracking.java
- backend/src/main/java/peer/backend/service/ExcelService.java
- backend/src/main/java/peer/backend/service/UserService.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- 엑셀 다운로드 기능에 유저 활동 추적 시트를 추가하였습니다.
- 모집 게시글을 작성했을때 해당 활동을 유저 활동 추적 테이블에 저장합니다.
<br><br><br>
> [FEATURE] 유저 활동 추적 엑세 다운로드 & 모집 게시글 작성 추적

- backend/src/main/java/peer/backend/dto/temp/RequestDnDDTO.java
> FIX: mongo dto

- backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
- backend/src/main/java/peer/backend/controller/socket/SocketIoServerController.java
- backend/src/main/java/peer/backend/controller/temp/TempDnDController.java
- backend/src/main/java/peer/backend/dto/temp/RequestDnDDTO.java
- backend/src/main/resources/application-dev.yml
> FEAT: token, dto, https 변경사항 

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
getInterviewList에서 type 매핑하는 부분 주석 처리된 것 주석 기호 삭제
<br><br><br>
> HOTFIX #393 delete comment

- backend/src/main/java/peer/backend/config/jwt/JwtFilter.java
- backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
> hotfix: jwt token filter

- backend/build.gradle
- backend/src/main/java/peer/backend/config/RestTemplateConfig.java
- backend/src/main/java/peer/backend/service/file/ObjectService.java
- backend/src/test/java/peer/backend/team/TeamRepositoryTest.java
File 업로드를 nhn Object storage에 업로드 합니다
<br><br><br>
테스트 postMan으로 통과
> [FEAT] : Add nhn Object storage

- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- backend/src/main/java/peer/backend/service/file/ObjectService.java
모집글에 objectService를 적용하기 위한 수정
objectService에 함수 일부 private으로 수정
update용 타입에 맞게 수정 + validation 추가
<br><br><br>
> [FIX] 모집글에 storage 적용, objectService minor refactor

- backend/src/main/java/peer/backend/entity/team/Team.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 이미지 변경을 ObjectService를 사용하도록 변경합니다
<br><br><br>
PostMan 확인
> refactor: uploadImage to nhn Object Storage

- backend/src/main/java/peer/backend/service/team/TeamService.java
원본이미지 주소와 같을 때 함수가 종료되게 합니다
<br><br><br>
postman 성공
> [HOTFIX]: changeImage And OriginalImage same

- backend/src/main/java/peer/backend/aspect/ActivityTrackingAspect.java
- backend/src/main/java/peer/backend/aspect/UserTrackingAspect.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/team/TeamUser.java
- backend/src/main/java/peer/backend/service/MemberService.java
- 유저 활동 추적에서 탈퇴 추적 기능
- 유저 탈퇴를 위한 리팩토링
<br><br><br>
> [FEAT] 유저 활동 추적에서 탈퇴 추적 & 유저 탈퇴를 위한 리팩토링

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
RecruitUpdateResponse에 isAnswerd 필드와 추가 코드 작성하고 이름을 isAnswered로 맞추기 위해 @JsonProperty와 @JsonPropertyIgnore 추가
<br><br><br>
> [HOTFIX] #403 인터뷰에 응답이 된 경우 인터뷰를 수정 금지

- backend/src/main/java/peer/backend/dto/team/TeamSettingDto.java
- backend/src/main/java/peer/backend/repository/team/TeamUserRepository.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀원 목록이 제대로 불러와지지 않은 현상을 수정합니다
<br><br><br>
postMan으로 통과
> [HOTFIX}: getTeamSetting Api

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- 모집글 생성 완료시 리다이렉션을 위하여 Recruit_id 반환하도록 수정하였습니다.
- 그외 소소한 리팩토링
<br><br><br>
> [HOTFIX] 모집글 생성 완료시 Recruit_id 반환

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
user nickname과 image를 Null로 매핑하여 전달.
<br><br><br>
> [HOTFIX] #406 모집게시글 조회할 때 작성자가 탈퇴한 유저인 경우

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitListRequest.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
- backend/src/main/java/peer/backend/entity/board/recruit/RecruitInterview.java
> [HOTFIX] #230 recruit 관련 엔티티와 dto validation 일괄 추가

- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
objectService.deleteObject(recruit.getThumbnailImage());
<br><br><br>
> [HOTFIX] #418 모집글 삭제시 대표이미지 삭제

- backend/src/main/java/peer/backend/controller/team/TeamController.java
- backend/src/main/java/peer/backend/entity/team/Team.java
- backend/src/main/java/peer/backend/repository/team/TeamRepository.java
- backend/src/main/java/peer/backend/repository/team/TeamUserRepository.java
- backend/src/main/java/peer/backend/service/team/TeamService.java
팀 관련 코드 리펙터링 입니다
팀원 권한 설정에서 자기자신은 변경할 수 없게 합니다
<br><br><br>
> Refactor team controller

- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
> [HOTFIX] 이미지 단건 조회시 대표 이미지url을 dto에 추가하여 반환

- backend/src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- backend/src/main/java/peer/backend/entity/board/recruit/Recruit.java
팀 이름 최소값 validation 변경, recruitid와 teamId를 mapsId로 연동
<br><br><br>
> fix : team name min valid, recruit and team id mapsId

- backend/src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
- backend/src/main/java/peer/backend/service/UserService.java
이제 OAuth 연동시에 2중 연동 여부를 체크합니다. if문이 좀 더러운데 깔끔하게 할 방법이 안떠오르네요...
<br><br><br>
> [FIX] OAuth 2중 연동 체크

- backend/src/main/java/peer/backend/service/profile/KeywordAlarmService.java
- 기존 로직에서 수정하여, 각 내부의 키워드를 정확하게 확인하는 방식으로 수정
- Postman 등의 수동 접근을 대비하여 backend로직에서도 키워드 사이즈 제한 적용(최대 30자)
- Postman 등의 수동 접근, 자동화로 키워드 무한 입력을 제거 하고자 최대 키워드 개수는 10개로 제한함
- 
<br><br><br>
> [BUG] Adding Keyword duplication issue #431

- backend/src/main/java/peer/backend/controller/message/MessaageController.java
- backend/src/main/java/peer/backend/service/message/MessageSubService.java
- 프론트 요청대로 ISO 8601 양식으로 시간 전달하는 것으로 수정 
<br><br><br>
> [HOTFIX] message LocalDateTime

- backend/src/main/java/peer/backend/controller/board/RecruitController.java
- backend/src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
- 모집글 단건조회 response에 isFavorite과 teamName 추가
- 소소한 리팩터
<br><br><br>
postman
> [HOTFIX] add isFavorite & teamName to response of getRecruit service method

- src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
OAuth 로그인에 성공했을때 발급하는 쿠키를 Secure Cookie로 수정하였습니다.
<br><br><br>
> [FIX] secure cookie

- src/main/java/peer/backend/service/board/recruit/RecruitService.java
토큰이 존재하지 않을때 user를 불러와서 nullpointerexception이 발생하여 해당 부분 삭제 후
조건문 안에서 user를 불러오도록 수정
<br><br><br>
> [HOTFIX] get-single-recruit-without-token

- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- RecruitFavoritePK에 user_id, recruit_id 순서로 들어가야 하는데 반대로 들어가 있어서 수정
- 소소한 리팩토링
<br><br><br>
> [HOTFIX] getRecruit시 isFavorite이 false로만 응답되는 현상 수정

- src/main/java/peer/backend/controller/board/ShowcaseController.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
- favorite시 favorite 여부 boolean으로 리턴
- like시 like 개수 int로 리턴
<br><br><br>
> [HOTFIX] showcase favorite, like시 return value 수정

- src/main/java/peer/backend/dto/board/recruit/RecruitRoleDTO.java
- src/main/java/peer/backend/entity/board/recruit/Recruit.java
role.name -> role.role
<br><br><br>
> [HOTFIX] #481 hotfix recruit 작성시 프론트와 안맞는 dto 동기화

- src/main/java/peer/backend/dto/board/recruit/RecruitRoleDTO.java
- src/main/java/peer/backend/entity/board/recruit/Recruit.java
> [HOTFIX] field name revert

- src/main/java/peer/backend/dto/team/TeamInfoResponse.java
- src/main/java/peer/backend/service/team/TeamService.java
- code bug로 지정된 부분 수정하여, DB에서 가져올 때 isPresent를 확인하도록 함. 
- return 시 처리는 구조가 달라 조만간 리펙토링 필요 할듯 
<br><br><br>
> 448 bug teaminforesponse

- src/main/java/peer/backend/controller/message/MessaageController.java
> 446 bug message controller

- src/main/java/peer/backend/controller/TagController.java
- src/main/java/peer/backend/controller/board/RecruitController.java
- src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
- src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- src/main/java/peer/backend/dto/board/team/ShowcaseListResponse.java
- src/main/java/peer/backend/dto/tag/TagResponse.java
- src/main/java/peer/backend/entity/board/recruit/Recruit.java
- src/main/java/peer/backend/entity/composite/RecruitTagPK.java
- src/main/java/peer/backend/entity/tag/RecruitTag.java
- src/main/java/peer/backend/entity/tag/Tag.java
- src/main/java/peer/backend/repository/TagRepository.java
- src/main/java/peer/backend/service/TagService.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
- src/main/java/peer/backend/service/profile/FavoriteService.java
- src/test/java/peer/backend/board/ShowcaseServiceTest.java
recruit의 Tag를 admin의 tag를 사용하도록 리팩토링 하였습니다.
<br><br><br>
recruit 업데이트 부분에 코드가 최신화가 안되있는것 같아 업데이트를 제외하고 post, get 모두 테스트 완료하였습니다.
> [REAFCTOR] recruit의 Tag를 admin의 tag를 사용하도록 리팩토링

- src/main/java/peer/backend/entity/board/recruit/Recruit.java
- src/main/java/peer/backend/entity/tag/RecruitTag.java
- src/main/java/peer/backend/oauth/PrincipalDetails.java
- src/main/java/peer/backend/repository/board/recruit/RecruitRepository.java
- src/main/java/peer/backend/repository/board/recruit/RecruitTagRepository.java
- src/main/java/peer/backend/service/TagService.java
- src/main/java/peer/backend/service/UserDetailsServiceImpl.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
> [FIX] 태그 삭제할때 에러, 어드민 권한 검사 수정하였습니다.

- src/main/java/peer/backend/controller/ReportController.java
- src/main/java/peer/backend/converter/BacklistTypeConverter.java
- src/main/java/peer/backend/converter/ReportProcessingStatusConverter.java
- src/main/java/peer/backend/dto/report/ReportProcessingRequest.java
- src/main/java/peer/backend/entity/blacklist/Blacklist.java
- src/main/java/peer/backend/entity/blacklist/BlacklistType.java
- src/main/java/peer/backend/entity/report/ReportProcessingType.java
- src/main/java/peer/backend/repository/blacklist/BlacklistRepository.java
- src/main/java/peer/backend/repository/report/ReportRepository.java
- src/main/java/peer/backend/service/blacklist/BlacklistService.java
- src/main/java/peer/backend/service/report/ReportService.java
#476 
https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=46376573
- blacklist entity를 추가하고 관련 Enum, repository도 구현하였습니다.
- 신고 처리에서 영구밴도 처리하도록 추가하였습니다. blacklist에서 user_id가 unique함을 보장하도록 구현하였습니다.
- 신고하기에서 user 존재 체크가 잘 안되어 수정하였습니다.
<br><br><br>
포스트맨으로 테스트 완료하였습니다.
> [FEATURE] blacklist entity & 신고 처리(영구밴)

- src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- src/main/java/peer/backend/entity/board/recruit/enums/RecruitInterviewType.java
- src/main/java/peer/backend/entity/team/enums/TeamUserStatus.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
Enum 타입 프론트와 동기화
모집글 업데이트 페이지 들어갔을 때 반환 데이터 추가
단순 hotfix로 강제 머지합니다.
<br><br><br>
> hotfix-some of interviewTypeEnum name change and add type

- src/main/java/peer/backend/entity/board/recruit/enums/RecruitInterviewType.java
단순 이름 변경이라서 강제머지 합니다.
<br><br><br>
> fix:change

- src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
단순 핫픽스(responseBody에 name field 추가)이므로 ci/cd통과 후 강제머지합니다.
<br><br><br>
> hotfix-add name field to RecruitUpdateResponse

- src/main/java/peer/backend/config/SecurityConfig.java
기존에 tag list를 불러올때 토큰이 필요했는데 이를 필요 없도록 수정하였습니다.
<br><br><br>
> [FIX] tag list 권한 수정

- src/main/java/peer/backend/entity/team/Team.java
- src/main/java/peer/backend/service/team/TeamService.java
memberValue 초기화 및 인원수 계산을 위하여
엔티티 로드시 jobs의 max를 sum으로 계산합니다.
핫픽스를 위한 사소한 변경이라서 ci/cd통과하여 강제머지 하겠습니다.
<br><br><br>
> [Hotfix] pre update team max member value

- src/main/java/peer/backend/config/SecurityConfig.java
- src/main/java/peer/backend/config/jwt/ExceptionHandlerFilter.java
- src/main/java/peer/backend/config/jwt/JwtFilter.java
- src/main/java/peer/backend/controller/BlacklistController.java
- src/main/java/peer/backend/controller/ReportController.java
- src/main/java/peer/backend/converter/ReportProcessingStatusConverter.java
- src/main/java/peer/backend/dto/blacklist/AddBlacklistRequest.java
- src/main/java/peer/backend/dto/blacklist/BlacklistResponse.java
- src/main/java/peer/backend/dto/blacklist/HandleBlacklistRequest.java
- src/main/java/peer/backend/dto/report/ReportHandleRequest.java
- src/main/java/peer/backend/entity/blacklist/BlacklistHandleType.java
- src/main/java/peer/backend/entity/report/ReportHandleType.java
- src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
- src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
- src/main/java/peer/backend/oauth/enums/LoginStatus.java
- src/main/java/peer/backend/repository/blacklist/BlacklistRepository.java
- src/main/java/peer/backend/service/LoginService.java
- src/main/java/peer/backend/service/blacklist/BlacklistService.java
#476 
https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=46376829
https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=46377346
https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=46377491
- 블랙리스트 가져오기(Pagenation)
- 블랙리스트 추가하기
- 블랙리스트 처리하기(석방)
- 블랙리스트 로그인/OAuth 블락처리
구현사항은 위와 같습니다.
<br><br><br>
> [FEATURE] 어드민 블랙리스트 관련 api 구현

- src/main/java/peer/backend/service/board/recruit/RecruitService.java
team으로 이동한 Recruit의 필드들을 조회하는 쿼리 수정
<br><br><br>
> hotfix: getRecruitList query

- src/main/java/peer/backend/entity/team/Team.java
> hotfix - add Enumerated annotation to RecruitDueEnum of TeamEntity

- src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
recruit 수정페이지 진입시 responseBody에 해당 게시글의 imageUrl을 추가합니다.
<br><br><br>
> hotfix-add image field to RecruitUpdateResponse

- src/main/java/peer/backend/controller/board/RecruitController.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
모집글 업데이트시 게시글 id 반환
<br><br><br>
> [FIX] return recruit id after recruit updated

- src/main/java/peer/backend/annotation/ValidDateTime.java
- src/main/java/peer/backend/controller/NoticeController.java
- src/main/java/peer/backend/converter/NoticeStatusConverter.java
- src/main/java/peer/backend/converter/NotificationConverter.java
- src/main/java/peer/backend/dto/notice/CreateNoticeRequest.java
- src/main/java/peer/backend/dto/notice/NoticeIdRequest.java
- src/main/java/peer/backend/dto/notice/NoticeListResponse.java
- src/main/java/peer/backend/dto/notice/NoticeResponse.java
- src/main/java/peer/backend/dto/notice/UpdateNoticeRequest.java
- src/main/java/peer/backend/entity/notice/Notice.java
- src/main/java/peer/backend/entity/notice/NoticeStatus.java
- src/main/java/peer/backend/entity/notice/Notification.java
- src/main/java/peer/backend/repository/notice/NoticeRepository.java
- src/main/java/peer/backend/service/NoticeService.java
- src/main/java/peer/backend/service/file/ObjectService.java
- src/main/java/peer/backend/validator/DateTimeValidator.java
#511 
- 공지사항 리스트
- https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46479471
- 공지사항 보기
- https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46481429
- 공지사항 작성
- https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46480201
- 공지사항 삭제
- https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46482297
- 공지사항 수정
- https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46482958
- 공지사항 숨기기
-  https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46719898
- 공지사항 숨기기 해제
-  https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46720275
위 API들을 구현하였으며 추가로 공지사항 알림, 알림 예약, 공지사항 예약이 구현되어야 하나 알림 쪽을 붙일 수 있을때 작업해야하여 보류된 상태입니다.
<br><br><br>
> [FEATURE] 어드민 공지사항 API 개발

- src/main/java/peer/backend/controller/board/RecruitController.java
@authorcheck 어노테이션에 Authentication을 전해주기 위해서 메소드 인자로 추가
<br><br><br>
> [HOTFIX] add Authentication parameter to updateRecruit method

- src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- src/main/java/peer/backend/service/team/TeamService.java
모집글 생성시 작성자에게 자동으로 리더 역할 부여
* createRequest에서 leaderJob 삭제
* teamJob과 teamUserJob을 Leader로 생성
<br><br><br>
> [fix] assign default leader to author when create recruit

- src/main/java/peer/backend/repository/banner/BannerRepository.java
- src/main/java/peer/backend/repository/notice/NoticeRepository.java
- src/main/java/peer/backend/scheduler/AdminScheduler.java
- src/main/java/peer/backend/scheduler/JobScheduler.java
- src/main/java/peer/backend/service/BannerService.java
- src/main/java/peer/backend/service/NoticeService.java
- src/main/java/peer/backend/service/UtilService.java
#526 
1분마다 예약 시간이 현재 시간을 지났는지 체크하다가 이를 게재 상태로 바꾸는 스케쥴링을 구현하였습니다.
<br><br><br>
> [FEATURE] 공지사항, 배너 게재 상태 변경 스케쥴링

- src/main/java/peer/backend/controller/dnd/DnDController.java
> HOTFIX: DnD API Read method changed

- .github/workflows/test_ci_cd.yml
> Create test_ci_cd.yml #538

- src/main/java/peer/backend/converter/NotificationConverter.java
- src/main/java/peer/backend/dto/notice/CreateNoticeRequest.java
- src/main/java/peer/backend/dto/notice/NoticeListResponse.java
- src/main/java/peer/backend/dto/notice/NoticeResponse.java
- src/main/java/peer/backend/entity/banner/Banner.java
- src/main/java/peer/backend/entity/notice/Notice.java
- src/main/java/peer/backend/entity/notice/NoticeNotification.java
- src/main/java/peer/backend/repository/notice/NoticeRepository.java
- src/main/java/peer/backend/scheduler/AdminScheduler.java
- src/main/java/peer/backend/service/NoticeService.java
공지사항 & 배너 게재가 될 시 createdAt을 갱신하도록 수정하였습니다.
notice의 notification, status 필드명을 좀 더 명확하게 수정하였습니다.
<br><br><br>
> [REFACTOR] 공지사항 & 배너 게재가 될 시 createdAt을 갱신하도록 리팩토링

- src/main/java/peer/backend/converter/BannerStatusConverter.java
- src/main/java/peer/backend/dto/banner/UpdateBannerRequest.java
- src/main/java/peer/backend/entity/banner/Banner.java
- src/main/java/peer/backend/repository/banner/BannerRepository.java
- src/main/java/peer/backend/repository/notice/NoticeRepository.java
- src/main/java/peer/backend/scheduler/AdminScheduler.java
- src/main/java/peer/backend/scheduler/JobScheduler.java
- src/main/java/peer/backend/service/BannerService.java
- src/main/java/peer/backend/service/NoticeService.java
- src/main/java/peer/backend/service/UtilService.java
> 526 feature scheduling

- .github/workflows/test_ci_cd.yml
도커에서 키 값이 아닌, 개인 서버에서 로그인하는데 필요한 비밀번호를 요구.
시크릿에 비밀번호 추가.
<br><br><br>
> [Fix] : access login with user pw #538

- src/main/java/peer/backend/controller/dnd/DnDController.java
- src/main/java/peer/backend/service/dnd/DnDService.java
- DnD Read API 의 return value 를 프론트에서 요청하는 걸로 변경
- 모든 DnDApi 에 대해 team member 가 API를 요청했는지 점검하는 로직 추가
<br><br><br>
> 542 bug dnd team security enhancement

- src/main/java/peer/backend/service/profile/FavoriteService.java
- profile 에서 관심리스트 부분에서 500 error 발생
- 이에대해 확인해보니 FavorinteService 쪽에서 Entity Manager를 활용하는 부분에서 에러 발생
- 해당 에러를 확인해보니 DB 구조에서 기존에 있던 type 이 삭제 되면서 수정 대응이 안된것으로 파악
- 이에 관심 리스트를 검색함에 있어, 기존 구조를 최대한 일단 유지하고자, Team 테이블을 추가 Join하여 필요한 TeamType 을 받아오는 것으로 하여 DB 연결을 복구함.
<br><br><br>
> FIX: favorite Api error fixed

- .github/workflows/test_ci_cd.yml
docker username 자리에 호스트 유저네임이 오기입
<br><br><br>
> [Fix] : omitting env val

- src/main/java/peer/backend/dto/profile/request/EditProfileRequest.java
- src/main/java/peer/backend/entity/user/User.java
1) 프로필 소개 문구 150자 제한을 위해 DTO 에 유효성 검사 어노테이션 추가 
2) 닉네임이 너무 짧아  DTO 및 User 엔티티 글자수 제한 수정
<br><br><br>
> 555 bug profile introduction input

- src/main/java/peer/backend/annotation/tracking/BlacklistFreeTracking.java
- src/main/java/peer/backend/annotation/tracking/UserBanTracking.java
- src/main/java/peer/backend/annotation/tracking/UserReportTracking.java
- src/main/java/peer/backend/aspect/UserTrackingAspect.java
- src/main/java/peer/backend/mongo/repository/UserTrackingRepository.java
- src/main/java/peer/backend/service/blacklist/BlacklistService.java
- src/main/java/peer/backend/service/report/ReportService.java
#554 
사용자 추적 파트에서 기능이 개발되지 않아 개발하지 못했던 부분들을 추가 개발하였습니다.
위와 같은 부분들을 개발하였습니다.
<br><br><br>
> [FEATURE] 사용자 추적 파트 추가 개발

- src/main/java/peer/backend/config/jwt/TokenProvider.java
- src/main/java/peer/backend/controller/socket/SocketIoServerController.java
- src/main/java/peer/backend/dto/socket/whoURDTO.java
- src/main/java/peer/backend/dto/socket/yesWhoUAreDTO.java
- src/main/java/peer/backend/service/socket/SocketServerService.java
- 소켓 이벤트 작성 
- 해당 소켓 이벤트를 활용하면 사용자의 ID 혹은 소속 팀 정보를 제공 시 팀 내의 멤버인지 리더인지를 전달해줍니다 
- 해당 기능 문서화 하여 전달 예정
<br><br><br>
> 550 feature socket event listener

- .github/workflows/test_ci_cd.yml
- Dockerfile-test
80번 포트 점유 문제로 8080으로 임시 사용,
포트 80 번 문제가 해결되면, 환경변수로 값 교체하기 편하게 환경변수화
com4에 데이터베이스들 정상작동 중.
프로파일 로컬 방식으로 연결하려 함.
<br><br><br>
> [Fix] com4 cicd 파일 수정

- src/main/java/peer/backend/annotation/tracking/PostCreateTracking.java
- src/main/java/peer/backend/aspect/ActionTrackingAspect.java
- src/main/java/peer/backend/controller/board/BoardController.java
- src/main/java/peer/backend/controller/board/RecruitController.java
- src/main/java/peer/backend/mongo/entity/enums/ActionTypeEnum.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/board/team/BoardService.java
#561 
팀 게시판에 글쓰는 행동을 추적합니다.
한 줄에 100글자 넘는거 reformat 된 부분들이 많은데 그 부분은 뺴고 보시면 됩니다.
<br><br><br>
> [FEATURE] 팀 게시판 글쓰기 추적

- Dockerfile-test
테스트 서버 com4 상황이 Local 프로파일과 다른 점이 있어
yml 파일을 새로 생성했습니다.
기존에 application-dev에 있는 호스트에 새로운 메인서버 주소를 넣는 방향.
<br><br><br>
> Test 서버 설정 파일 dev 브랜치에 머지

- src/main/java/peer/backend/controller/team/TeamController.java
- src/main/java/peer/backend/dto/team/TeamJobSettingDto.java
- src/main/java/peer/backend/dto/team/TeamSettingDto.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/team/TeamService.java
* 신청자 승인, 거절 로직 변경
* 팀 세팅값 불러올때 job들도 같이 불러올 수 있도록 수정
* 쿼리문의 일치하지 않는 변수 이름 수정
<br><br><br>
> [hotfix] accept&reject-logic-add-jobs-when-get-team-setting

- src/main/java/peer/backend/dto/team/TeamMemberDto.java
- src/main/java/peer/backend/dto/team/TeamSettingDto.java
team의 setting 값을 불러올 때 member에 job list를 넣어서 반환
<br><br><br>
> [hotfix]-team-get-setting-dto

- src/main/java/peer/backend/dto/team/TeamApplicantListDto.java
- src/main/java/peer/backend/service/team/TeamService.java
지원자가 어떤 역할에 지원했는지 구별하기 위하여 jobName을 response body에 추가
<br><br><br>
> [hotfix] add-jobname-to-applicantList

- src/main/java/peer/backend/config/RedisRepositoryConfig.java
- src/main/java/peer/backend/controller/dnd/DnDController.java
- src/main/java/peer/backend/dto/dnd/TeamMember.java
- src/main/java/peer/backend/entity/BaseEntity.java
- src/main/java/peer/backend/service/dnd/DnDService.java
- redis configuration 이 비정상 설정으로 수정하였습니다.
- redis 직렬화 역직렬화가 java 8 기준 LocalDateTime 의 직렬화 역직렬화 가 호환되지 못합니다.
- 위의 조건 때문에 기존의 TeamUser 를 쓰지 않고, TeamUser Status 만 Approved 된 사람들을 따로 모을 수 있는 TeamMember 라는 객체를 만들어 활용하여 valid checking 을 수행하도록 수정하였습니다.
- Redis 저장을 위한 key 패턴을 기존에 정한 패턴과 동일한 구조로 수정하였습니다. 
- BaseEntity 에 Redis에 호환되지 못하는 문제를 해결하고자 Json 직렬화, 역직렬화를 돕는 어노테이션을 추가하였습니다.(해당 부분은 실험적입니다. 수정 이후 문제 시 롤백 예정)
<br><br><br>
> 578 bug dnd read create api 500 error

- .github/workflows/ci_cd.yml
> Repository dispatch test

- src/main/java/peer/backend/controller/socket/SocketIoServerController.java
> FIX: socket event return way

- build.gradle
> TEST: hotfix build gradle

- src/main/java/peer/backend/repository/board/team/PostRepository.java
db 쿼리에 맞게 수정했습니다.
<br><br><br>
> [Fix] : fix taste for dbs #606

- src/main/java/peer/backend/controller/team/TeamController.java
- src/main/java/peer/backend/dto/team/TeamIdRequest.java
- src/main/java/peer/backend/dto/team/TeamJobUpdateDto.java
- src/main/java/peer/backend/entity/team/Team.java
- src/main/java/peer/backend/entity/team/TeamUser.java
- src/main/java/peer/backend/entity/team/enums/TeamStatus.java
- src/main/java/peer/backend/repository/team/TeamUserRepository.java
- src/main/java/peer/backend/service/TeamUserService.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/board/team/BoardService.java
- src/main/java/peer/backend/service/team/TeamService.java
팀 설정 페이지에서 미구현된 부분들을 추가 구현하였습니다.
#587 
- 팀 나가기
- 팀 해산하기
- 팀 완료하기
위 API들을 추가 구현하였고,
- 팀 역할 추가
- 팀 역할 수정
- 팀 역할 삭제
위 API들을 리팩토링 하였습니다.
<br><br><br>
> [FEATURE] 팀 설정 페이지 추가 구현

- src/main/java/peer/backend/controller/profile/PersonalInfoController.java
- src/main/java/peer/backend/dto/profile/request/ChangePasswordRequest.java
- src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
- src/main/java/peer/backend/service/MemberService.java
- src/main/java/peer/backend/service/profile/PersonalInfoService.java
- src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
기존에 현재 비밀번호, 새 비밀번호를 한 번에 받아 변경을하던 로직에서 현재 비밀번호 확인 -> 비밀번호 변경으로 로직을 변경하였습니다.
<br><br><br>
> [REFACTOR] 비밀번호 변경 리팩토링

- .github/workflows/test_ci_cd.yml
- src/main/java/peer/backend/controller/team/TeamPageController.java
- src/main/java/peer/backend/service/teampage/TeamPageService.java
> getPosts 페이지 타입으로 반환

- src/main/java/peer/backend/controller/profile/ProfileController.java
- src/main/java/peer/backend/dto/profile/SkillDTO.java
- src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
- src/main/java/peer/backend/entity/tag/UserSkill.java
- src/main/java/peer/backend/entity/tag/UserSkills.java
- src/main/java/peer/backend/entity/user/User.java
- src/main/java/peer/backend/repository/TagRepository.java
- src/main/java/peer/backend/repository/user/UserRepository.java
- src/main/java/peer/backend/repository/user/UserSkillsRepository.java
- src/main/java/peer/backend/service/profile/ProfileService.java
- tag 기반 skill 속성 User 추가, UserSkill DB 테이블 추가
- skill 검색 API 추가
- keyword validation 추가 
- skill 설정 API 추가
- user 당 최대 10개로 skill 추가 유효성 검사 추가
- 기타 중복 체크 등 추가
- skill 갯수가 적으므로 Eager 방식으로 데이터 로딩하도록 설정
- Profile get API 수정 
- skill List DTO에 맞게 수정
<br><br><br>
> 610 refactor myprofile skill tag modify

- src/main/java/peer/backend/controller/board/BoardController.java
- src/main/java/peer/backend/dto/board/team/PostCommentRequest.java
- src/main/java/peer/backend/entity/board/team/Post.java
- src/main/java/peer/backend/service/board/team/BoardService.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
postAnswer create service, controller
<br><br><br>
> [Feat] post answer create

- src/main/java/peer/backend/controller/board/BoardController.java
- src/main/java/peer/backend/dto/board/team/PostCommentUpdateRequest.java
- src/main/java/peer/backend/entity/board/team/Post.java
- src/main/java/peer/backend/entity/board/team/PostComment.java
- src/main/java/peer/backend/repository/board/team/PostAnswerRepository.java
- src/main/java/peer/backend/repository/board/team/PostCommentRepository.java
- src/main/java/peer/backend/service/board/team/BoardService.java
> [Feat] update comment

- src/main/java/peer/backend/dto/team/TeamListResponse.java
- src/main/java/peer/backend/entity/board/team/enums/BoardType.java
- src/main/java/peer/backend/service/team/TeamService.java
* isApproved 추가
* team 생성시 공지사항 board 추가
<br><br><br>
> [Hotfix] modify team list validation

- src/main/java/peer/backend/dto/board/recruit/HitchListResponse.java
- src/main/java/peer/backend/service/board/recruit/HitchHikingService.java
author image를 response dto에 추가하였습니다.
탈퇴한 유저인 경우 해당 필드를 null로 반환합니다.
<br><br><br>
> [Hotfix] #627 add authorImage to HitchListResponse

- src/main/java/peer/backend/controller/board/BoardController.java
- src/main/java/peer/backend/service/board/team/BoardService.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
* delete comment
* getShowcaseList 리팩토링
<br><br><br>
postman
> [Feat] delete comment

- src/main/java/peer/backend/dto/profile/SkillDTO.java
- src/main/java/peer/backend/entity/tag/UserSkill.java
- src/main/java/peer/backend/repository/user/UserSkillRepository.java
- src/main/java/peer/backend/repository/user/UserSkillsRepository.java
- src/main/java/peer/backend/service/profile/ProfileService.java
> HOTFIX skill regist

- src/main/java/peer/backend/service/profile/ProfileService.java
제곧네입니다. 
빈배열 올시 데이터만 전체 삭제를 진행합니다. 
<br><br><br>
> HOTFIX: empty list adopted

- src/main/java/peer/backend/service/profile/UserPortfolioService.java
- 포트폴리오 페이지 값을 0에서 1로 바꿈
<br><br><br>
> change page start value 0 to 1

- src/main/java/peer/backend/controller/profile/FavoriteController.java
- src/main/java/peer/backend/dto/profile/FavoritePage.java
- src/main/java/peer/backend/dto/profile/SkillDTO.java
- src/main/java/peer/backend/dto/profile/response/RecruitFavoriteDto.java
- src/main/java/peer/backend/entity/tag/RecruitTag.java
- src/main/java/peer/backend/repository/board/recruit/RecruitFavoriteRepository.java
- src/main/java/peer/backend/service/board/recruit/HitchHikingService.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
- src/main/java/peer/backend/service/profile/FavoriteService.java
관심리스트 조회 서비스 로직 변경
<br><br><br>
> [Hotfix] get favorites in profile

- .github/workflows/ci_cd.yml
- .github/workflows/test_ci_cd.yml
> [Fix] : 배포 지정 대상 수정 #643

- src/main/java/peer/backend/controller/profile/FavoriteController.java
- src/main/java/peer/backend/dto/profile/response/RecruitFavoriteDto.java
- src/main/java/peer/backend/service/profile/FavoriteService.java
관심리스트의 모집글 작성자 정보를 로그인 유저 정보로 전달하던 것 수정
<br><br><br>
> [Hotfix] change user info -> writer info

- src/main/java/peer/backend/entity/tag/Tag.java
- src/main/java/peer/backend/service/TagService.java
#649 
원래 직접 태그의 이름이 존재하는지 찾아서 체크하던 방식에서 unique 위반시 발생되는 exception을 catch 하도록 수정하였습니다.
<br><br><br>
> [REFACTOR] 태그 이름 중복 체크 로직 변경

- src/main/java/peer/backend/config/SecurityConfig.java
- src/main/java/peer/backend/controller/AnnouncementController.java
- src/main/java/peer/backend/dto/announcement/AboutAnnouncementListResponse.java
- src/main/java/peer/backend/dto/announcement/AboutAnnouncementResponse.java
- src/main/java/peer/backend/repository/announcement/AnnouncementRepository.java
- src/main/java/peer/backend/service/AnnouncementService.java
#652
어바웃 페이지에서 일반 유저들이 볼 공지사항 API를 구현하였습니다
- 공지사항 리스트
- 공지사항 디테일
<br><br><br>
> [FEAT] 어바웃 페이지 공지사항 API

- src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
- src/main/java/peer/backend/dto/privateinfo/InitTokenDTO.java
- src/main/java/peer/backend/dto/privateinfo/MainSeedDTO.java
- src/main/java/peer/backend/dto/privateinfo/PrivateDataDTO.java
- src/main/java/peer/backend/dto/privateinfo/enums/PrivateActions.java
- src/main/java/peer/backend/service/PrivateInfoWrappingService.java
- logic and DTO 설정 
- seed, code 를 발급하는 로직 추가 구현 완료
<br><br><br>
> [FEAT] private info sealing feature 2

- src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
- src/main/java/peer/backend/dto/privateinfo/MainSeedDTO.java
- src/main/java/peer/backend/dto/privateinfo/PrivateDataDTO.java
- src/main/java/peer/backend/service/PrivateInfoWrappingService.java
- 제일 마지막 커밋만 보면 됩니다..! signup logic, password logic 주입 마무리
<br><br><br>
postman 으로 동작확인 완료
> [FEAT] private info sealing feature 3

- src/main/java/peer/backend/dto/profile/request/ChangePasswordRequest.java
- src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
- src/main/java/peer/backend/dto/security/UserInfo.java
- src/main/java/peer/backend/service/PrivateInfoWrappingService.java
- 모든 로직 작성 완료. 유효성 검사가 없는 상태입니다.
<br><br><br>
> [FEAT] private info sealing feature 4

- src/main/java/peer/backend/controller/team/TeamController.java
- src/main/java/peer/backend/dto/team/TeamSettingInfoDto.java
- src/main/java/peer/backend/entity/team/Team.java
- src/main/java/peer/backend/service/team/TeamService.java
#656 
- 팀 설정하기에서 enum, 해산이랑 완료 상태일때 팀 설정하기 방지
- 팀 완료 시 종료일 기록
<br><br><br>
> [REFACTOR] 팀 설정 페이지 짜잘 수정

- src/main/java/peer/backend/controller/board/ShowcaseController.java
- src/main/java/peer/backend/dto/board/team/ShowcasePageInfoResponse.java
- src/main/java/peer/backend/entity/board/team/Post.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
* getShowcasePageInfo - 팀설정페이지에서 쇼케이스 페이지를 위한 정보 조회
* changeShowcasePublic - 쇼케이스 공개 여부 설정
<br><br><br>
> feat:getShowcasePageInfo, changetShowcasePublic api

- src/main/java/peer/backend/controller/team/TeamPageController.java
- src/main/java/peer/backend/repository/board/team/BoardRepository.java
- src/main/java/peer/backend/service/board/team/BoardService.java
- src/main/java/peer/backend/service/teampage/TeamPageService.java
https://github.com/peer-42seoul/Peer-Backend/issues/625
<br><br><br>
> [FEAT] 팀 페이지 공지사항 게시판 글 작성과 목록보기

- src/main/java/peer/backend/controller/board/ShowcaseController.java
- src/main/java/peer/backend/dto/board/team/ShowcaseUpdateDto.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
image가 null인 경우 이미지 수정이 없는 것으로 간주하여 이미지를 업데이트 하지 않음.
<br><br><br>
> [Hotfix] 쇼케이스 업데이트시 image가 null인 경우

- src/main/java/peer/backend/dto/profile/response/OtherProfileResponseDTO.java
- src/main/java/peer/backend/service/profile/ProfileService.java
- api 요청에 맞춰 email, 오타 수정(profileVisibility) 
<br><br><br>
> REFACTOR-mdoify-other-profile-api

- src/main/java/peer/backend/dto/board/recruit/RecruitInterviewDto.java
- src/main/java/peer/backend/entity/board/recruit/Recruit.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
…ptionList
options에서 optionList로 변경
<br><br><br>
> [Hotfix] RecruitInterviewDto의 option 필드 이름 변경

- src/main/java/peer/backend/service/teampage/TeamPageService.java
팀 유저 조건문에 부정조건문을 누락하여 수정합니다.
<br><br><br>
> [HOTFIX] : posting error fix #718

- src/main/java/peer/backend/controller/team/TeamPageController.java
- src/main/java/peer/backend/dto/board/team/BoardPostRes.java
기존에 포스트 아이디 반환과 함께 보드 아이디도 반환.
<br><br><br>
> [REFACTOR] : posting res adding boardId #721

- src/main/java/peer/backend/controller/team/TeamPageController.java
기존 게시글이 없을 때, 404를 반환하는 코드에서 빈 배열을 반환으로 협의 및 반영
<br><br><br>
> [Refactor] 714 feat team page empty post

- src/main/java/peer/backend/annotation/tracking/CompleteTeamTracking.java
- src/main/java/peer/backend/annotation/tracking/DisperseTeamTracking.java
- src/main/java/peer/backend/aspect/TeamTrackingAspect.java
- src/main/java/peer/backend/controller/team/TeamController.java
- src/main/java/peer/backend/service/team/TeamService.java
#662 
- 팀 해산하기
- 팀 완료하기
위 두 API에 따라 팀의 상태를 업데이트합니다.
<br><br><br>
> [FEATURE] 사용자 추적 모듈 추가 개발

- src/main/java/peer/backend/config/RedisRepositoryConfig.java
- src/main/java/peer/backend/controller/dnd/DnDSubController.java
- src/main/java/peer/backend/dto/dndSub/TeamIdentifierDTO.java
- src/main/java/peer/backend/service/dnd/DnDSubService.java
- 본 api 수정은 임시용입니다!!!
- 위젯에서 데이터를 가져오는 용 및 프론트엔드에서 테스트를 위한 간의 형태로 알람 모듈 업데이트 후 추가 수정될 예정입니다. 
<br><br><br>
> 724 hotfix dnd sub module hotfix

- src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
- src/main/java/peer/backend/controller/SignInController.java
- src/main/java/peer/backend/dto/privateinfo/enums/PrivateActions.java
- src/main/java/peer/backend/service/PrivateInfoWrappingService.java
- 로그인 API에 대해서 감싸기를 시전하였씁니다.
- 이제 로그인 정보는 어디서도 보이지 않도록 암호화 됩니다...! 
<br><br><br>
> FEAT: wrapped signIn api to privateInfoWrapping module

- src/main/java/peer/backend/controller/profile/FavoriteController.java
api가 변경되어 관심리스트의 endpoint를 recruit에서 mypage로 변경하였습니다.
<br><br><br>
> [Hotfix]change endpoint from recruit to endpoint

- .github/workflows/dev_ci_cd.yml
- 파일 이름 변경
- 쓸모없는 주석 삭제
- trigger branch에 main 삭제, release-** 추가
<br><br><br>
> [CHORE] dev ci cd 릴리즈 전략에 맞춰 수정

- src/main/java/peer/backend/config/SecurityConfig.java
- src/main/java/peer/backend/controller/board/HitchHikingController.java
- src/main/java/peer/backend/repository/board/recruit/RecruitRepository.java
- src/main/java/peer/backend/service/board/recruit/HitchHikingService.java
* 히치하이킹 목록에서 좋아요 또는 싫어요 된 게시물은 제외하도록 쿼리 수정
* 쇼케이스와 히치하이킹을 토큰 없이 조회 가능하도록 SecurityConfig 수정
<br><br><br>
> [Hotfix] exclude favorite from hitchhiking

- src/main/java/peer/backend/controller/message/MessaageController.java
- src/main/java/peer/backend/service/noti/NotificationSubService.java
- 기존 api 에 대해서 메시지 발생 경우, 알림을 작성하도록 만들었습니다.
<br><br><br>
- postman을 통해 데이터 생성 및 정상 작동 여부 확인 완료
> [FEAT] message 알림 추가하기 

- src/main/java/peer/backend/controller/SignInController.java
로그인 리스폰스 바디에서 필요없는 데이터를 삭제합니다.
- isLogin
- userId
<br><br><br>
> [FIX] 로그인 리스폰스 바디 수정

- src/main/java/peer/backend/dto/board/recruit/HitchListResponse.java
- src/main/java/peer/backend/service/board/recruit/HitchHikingService.java
히치하이킹리스트 dto에 authorId 추가
<br><br><br>
> fix:add authorId field to HitchListResponse

- src/main/java/peer/backend/controller/team/TeamPageController.java
- src/main/java/peer/backend/dto/team/PostDetail.java
게시판 상세보기 시 요청자와 작성자가 일치하는지 로직을 하고
아래 속성에 결과값을 추가 반환합니다.
속성 추가
isAuthor : boolean
<br><br><br>
> [Refactor] : post detail adding attr isAuthor bool type #736

- src/main/java/peer/backend/controller/profile/FavoriteController.java
- src/main/java/peer/backend/dto/profile/response/ShowcaseFavoriteResponse.java
- src/main/java/peer/backend/repository/board/team/PostLikeRepository.java
- src/main/java/peer/backend/repository/board/team/PostRepository.java
- src/main/java/peer/backend/service/profile/FavoriteService.java
> [Feat] add getFavoriteList of showcase

- src/main/java/peer/backend/controller/profile/FavoriteController.java
코드 일관성과 프론트 동기화를 위해 요청 파라미터의 이름을 pagesize에서 pageSize로 변경
<br><br><br>
> [Hotfix] change request parameter name from pagesize to pageSize

- src/main/java/peer/backend/controller/message/MessaageController.java
- src/main/java/peer/backend/controller/socket/SocketIoServerController.java
- src/main/java/peer/backend/dto/message/MsgContentDTO.java
- src/main/java/peer/backend/repository/message/MessageIndexRepository.java
- src/main/java/peer/backend/service/message/MessageMainService.java
- 외부 페이지에서 메시지 생성 가능하도록 API 추가
- 내부에서 알아서 새로운 메시지인지, 아닌지를 판단하고 메시지를 보내줍니다. 
<br><br><br>
- postman을 통한 테스트 완료
> 747 feat external page message api

- src/main/java/peer/backend/controller/board/BoardController.java
- src/main/java/peer/backend/repository/board/team/PostCommentRepository.java
- src/main/java/peer/backend/service/board/team/BoardService.java
Page<> -> List<> 로 바뀌면서 안 쓰는 패키지 또한 제거했습니다.
<br><br><br>
> [Fix] : comment res type changed #752

- src/main/java/peer/backend/service/board/team/BoardService.java
팀, 유저 아이디를 파라미터 순서 뒤섞임 이슈!
<br><br><br>
> [Fix] : hot-valid-member-params #757

- src/main/java/peer/backend/repository/announcement/AnnouncementRepository.java
- src/main/java/peer/backend/service/AnnouncementService.java
> hotfix: pageable amazing front vs back war

- src/main/java/peer/backend/service/PrivateInfoWrappingService.java
- 최근에 @sinryuji 님이 바꾸신 내용을 private module 에 그대로 적용 
<br><br><br>
> REFACTOR: sign up logic for private info wrapping module

- src/main/java/peer/backend/dto/banner/BannerResponse.java
> [FIX] 배너 보기에 공지사항 url 추가

- src/main/java/peer/backend/service/board/recruit/RecruitService.java
이전에 tag 엔티티 변경으로 인해서 메인페이지에서 tag로 모집글 조회가 안되는 현상이 있어
쿼리 생성하는 로직 일부를 수정하였습니다.
<br><br><br>
> [Hotfix]-modify-criteria-for-searching-tags

- src/main/java/peer/backend/config/SecurityConfig.java
- src/main/java/peer/backend/oauth/OAuthAuthenticationFailureHandler.java
#774 
OAuth를 실패한 경우에 대한 핸들링으로 리다이렉션을 추가하였습니다
<br><br><br>
> [FEATURE] Oauth 실패 핸들링

- src/main/java/peer/backend/service/message/MessageMainService.java
- 메시지 리스트, 메시지 최초 보내기가 비정상 작동됨
- tarnsational.mandatory 전략 때문으로 판단하고 transaction 수정
<br><br><br>
- postman을 통해 수정 완료
> Hotfix message errors check

- src/main/java/peer/backend/controller/object/ObjectController.java
- src/main/java/peer/backend/service/file/ObjectService.java
> feat: add uploadImage api

- src/main/java/peer/backend/controller/profile/ProfileController.java
- src/main/java/peer/backend/dto/profile/request/EditProfileRequest.java
- src/main/java/peer/backend/repository/user/UserRepository.java
- src/main/java/peer/backend/service/profile/ProfileService.java
- 에러 메시지가 보내지도록 변경하였습니다.
<br><br><br>
> Hotfix profile edit

- src/main/java/peer/backend/entity/team/Team.java
- src/main/java/peer/backend/service/team/TeamService.java
모집상태 변경을 위해 팀 상태 변경시 모집글 상태도 변경하도록 수정
<br><br><br>
> [Hotfix] change recruit status when status of team is change

- src/main/java/peer/backend/dto/message/KeywordDTO.java
- 기존 닉네임 검색 기준을 영어, 숫자에서 영어숫자한글까지로 확대함
<br><br><br>
> ADD: new regexp

- src/main/java/peer/backend/service/board/recruit/RecruitService.java
모집게시글 조회시 전체 인원값을 구하는 로직을 수정하였습니다.
teamJobs의 max값을 더하여 반환합니다.
<br><br><br>
> [Hotfix] recruit totalnumber

- src/main/java/peer/backend/controller/SignInController.java
- src/main/java/peer/backend/service/MemberService.java
- 임시 비밀번호에 대해 발급 시, 특수문자가 포함되지 않아, 비밀번호 변경이 안되는 문제 파악.
- 해당 API 로직에 특수문자를 집어넣는 로직 추가하여 마무리
<br><br><br>
- postman 으로 전체 문제 파악 및 수정 완료
> FIX: modify temporary password

- src/main/java/peer/backend/repository/user/UserSkillRepository.java
- src/main/java/peer/backend/service/TagService.java
태그 삭제할때 유저 스킬 삭제하도록 수정하였습니다.
<br><br><br>
> [FIX] 태그 삭제시 유저 스킬 삭제

- src/main/java/peer/backend/repository/team/TeamUserRepository.java
- src/main/java/peer/backend/service/teampage/TeamPageService.java
팀에 멤버인 유저가 공지사항 작성 요청을 하는 것을 막기.
<br><br><br>
> [Fix] : hot-valid-member-params #796

- src/main/java/peer/backend/dto/profile/response/ShowcaseFavoriteResponse.java
좋아요한 쇼케이스를 불러올때 postFilse가 아니라 post.image를 가져오도록 수정하였습니다
<br><br><br>
> [FIX] 좋아요한 쇼케이스 불러오는 에러 수정

- src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/team/TeamService.java
프론트 렌더링에 사용하기 위해서 모집글 리스트, 디테일 조회시 updatedAt 필드를 추가로 반환합니다.
<br><br><br>
> Hotfix add updated at to recruit list response and recruit response

- src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
- src/main/java/peer/backend/service/profile/ProfileService.java
> FIX: misspelling

- src/main/java/peer/backend/controller/SignInController.java
- src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
- src/main/java/peer/backend/dto/profile/response/ShowcaseFavoriteResponse.java
- src/main/java/peer/backend/repository/team/TeamUserRepository.java
- src/main/java/peer/backend/repository/user/UserSkillRepository.java
- src/main/java/peer/backend/service/EmailAuthService.java
- src/main/java/peer/backend/service/MemberService.java
- src/main/java/peer/backend/service/TagService.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/profile/ProfileService.java
- src/main/java/peer/backend/service/teampage/TeamPageService.java
> Release 1.0.1

- src/main/java/peer/backend/controller/board/RecruitController.java
- src/main/java/peer/backend/dto/board/recruit/ApplyRecruitRequest.java
- src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
- src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
- src/main/java/peer/backend/entity/board/recruit/Recruit.java
- src/main/java/peer/backend/entity/board/team/Post.java
- src/main/java/peer/backend/entity/team/Team.java
모집글 작성 및 수정시 팀이름 40글자 제한 validation 추가
<br><br><br>
> [Hotfix] 1.0.2 add validation recruit title and name

- src/main/java/peer/backend/repository/user/UserRepository.java
- 비활성화시킨 유저들을 검색할 수 없도록 조치를 취하였습니다. (User 에 activated 항목추가 및 검색 로직 수정)
<br><br><br>
> FIX: searching without non-activated user

- src/main/java/peer/backend/controller/profile/ProfileController.java
- 스킬 검색을 2자 제한에서 1자 ~ 15자 사이로 제한하였습니다. 
<br><br><br>
> ADD: skill tag searching with 1 word

- src/main/java/peer/backend/dto/announcement/CreateAnnouncementRequest.java
- src/main/java/peer/backend/dto/announcement/UpdateAnnouncementRequest.java
- src/main/java/peer/backend/dto/banner/CreateBannerRequest.java
- src/main/java/peer/backend/dto/banner/UpdateBannerRequest.java
- src/main/java/peer/backend/dto/tag/CreateTagRequest.java
- src/main/java/peer/backend/entity/announcement/Announcement.java
토스트에디터에 맞춰 long text로 변경합니다
<br><br><br>
> [FIX] 공지사항 content longtext로 변경

- src/main/java/peer/backend/entity/user/User.java
- src/main/java/peer/backend/service/profile/ProfileService.java
- 더미 id를 포함한 유저들에 대해서는 사용자 프로필 요청시 id 가 -1 전달 해주는 것으로 수정함
<br><br><br>
> FIX: other user profile api

- src/main/java/peer/backend/dto/announcement/CreateAnnouncementRequest.java
- src/main/java/peer/backend/dto/announcement/UpdateAnnouncementRequest.java
- src/main/java/peer/backend/dto/banner/CreateBannerRequest.java
- src/main/java/peer/backend/dto/banner/UpdateBannerRequest.java
- src/main/java/peer/backend/entity/announcement/Announcement.java
- src/main/java/peer/backend/entity/banner/Banner.java
어드민쪽 url 데이터 타입 변경
validation을 잘못해서 다시 수정했습니다
<br><br><br>
> [FIX] 어드민쪽 url 데이터 타입 변경, validation 수정

- src/main/java/peer/backend/entity/team/Team.java
- sonar cloud 지적 사항 수정 대응 
<br><br><br>
> FIX sonar critical parts

- src/main/java/peer/backend/dto/tag/CreateTagRequest.java
> [FIX] 태그 validation 수정

- src/main/java/peer/backend/entity/board/recruit/Recruit.java
- 어플리케이션 얌파일 수정으로 아파치 서버 업로드 제한을 128MB 로 상향 설정
<br><br><br>
> FIX : update image upload limittation

- src/main/java/peer/backend/service/team/TeamService.java
이미지가 바뀐 게 없는 경우 
return ; 으로 밑에 변경 메서드를 호출하지 않고 반환되어 데이터베이스에 저장되지 않는 상황이 발생.
조건 스코프 이전.
<br><br><br>
> 이미지가 바뀐 게 없는 경우 로직 수정

- src/main/java/peer/backend/repository/team/TeamUserRepository.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
물론이지 전.
오브젝트 스토리지 삭제 로직은 일주일 전 코드로써 잘 작동될 것 같아,
모집 상태와 팀 유저 상태 분기만 추가했습니다.
<br><br><br>
> 모집글 삭제 메서드 조건 추가

- src/main/java/peer/backend/service/board/recruit/RecruitService.java
준비됐지 정?
에러 메시지 내용을 변경하였습니다.
<br><br><br>
> [Chore] : 물론이지 윤 #837

- src/main/java/peer/backend/service/noti/NotificationMainService.java
- user entity 의 Alarm counter가 음수가 되는 경우 발생.
- 이에 alarm 카운터가 0으로 되도록 삭제하는 부분마다 로직 추가함 
<br><br><br>
> hotfix-minus-problem!

- src/main/java/peer/backend/annotation/ValidUserId.java
- src/main/java/peer/backend/aspect/ValidUserIdAspect.java
- src/main/java/peer/backend/entity/team/Team.java
- src/main/java/peer/backend/service/team/TeamService.java
userId -1인지를 검증하는 aop를 구현하였고 grant role api에서 유저 아이디가 팀에 속한 유저 아이디인지 검증하는 로직을 추가하였습니다.
<br><br><br>
> [FEATURE & FIX] userId -1 검증 aop 구현, grant role userId 검증 추가

- src/main/java/peer/backend/controller/noti/NotificationController.java
- src/main/java/peer/backend/repository/noti/NotificationTargetRepository.java
- src/main/java/peer/backend/service/noti/NotificationMainService.java
- 예약 알림으로 되어 있는 이벤트를 따로 JPQL  조건문을 수정하여 기준 날(요청 받는 날짜)  이전 날짜로 기록된 알림에 대해서만 보여주는 것으로 수정하였습니다.
<br><br><br>
> Hotfix alarm list get api

- src/main/java/peer/backend/controller/noti/NotificationController.java
- src/main/java/peer/backend/repository/noti/NotificationTargetRepository.java
- src/main/java/peer/backend/service/noti/NotificationMainService.java
> Revert "Hotfix alarm list get api"

- src/main/java/peer/backend/repository/user/UserRepository.java
> ADD; JPQL condition add

- src/main/java/peer/backend/controller/board/BoardController.java
- src/main/java/peer/backend/repository/team/TeamUserRepository.java
- src/main/java/peer/backend/repository/user/UserRepository.java
- src/main/java/peer/backend/service/PrivateInfoWrappingService.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- alarm redirection link modified
<br><br><br>
> Release 1.0.4

- src/main/java/peer/backend/controller/board/RecruitController.java
- src/main/java/peer/backend/controller/board/ShowcaseController.java
- src/main/java/peer/backend/repository/team/TeamUserRepository.java
- src/main/java/peer/backend/repository/user/UserRepository.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
- src/main/java/peer/backend/service/board/team/ShowcaseService.java
- src/main/java/peer/backend/service/noti/NotificationCreationService.java
- src/main/java/peer/backend/service/team/TeamService.java
- Notification issue fixed 
<br><br><br>
> Release 1.0.5

- src/main/java/peer/backend/dto/board/recruit/RecruitListRequest.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
프론트 요청으로 모집글 리스트 조회시 모집글의 type에 ALL이 추가되어 해당 부분에 대한 처리 추가
<br><br><br>
> fix: add condition about type of ALL of RecruitListRequest

- .github/workflows/dev_ci_cd.yml
- 신규 서버에 맞춰 prod CICD 수정 
- 신규 서버에 맞춰 대응 secret 수정 
<br><br><br>
> Release 1.0.500

- src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
- src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
메인페이지 모집글 리스트 반환 데이터에 팀타입, 멤버수, 생성일을 추가합니다.
<br><br><br>
> fix: add member and createdAt at RecruitListResponse

- src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
- src/main/java/peer/backend/service/board/recruit/RecruitService.java
모집글 단건조회시 반환 데이터에 팀타입을 추가합니다.
<br><br><br>
> fix: add teamType to RecruitResponse

- src/main/java/peer/backend/service/board/Job/JobService.java
JobListReponse의 content와 createdAt의 내용을 수정
<br><br><br>
> fix: switch field content
